In [1]:
import numpy as np
import pandas as pd
import re
import time

In [2]:
from urllib.request import urlopen
from urllib.parse import quote

In [3]:
from bs4 import BeautifulSoup
from selenium import webdriver

### 간편식사

In [4]:
driver=webdriver.Chrome('C:/scrap/chromedriver.exe')
driver.implicitly_wait(10)
url='http://cu.bgfretail.com/product/product.do?category=product&depth2=4&depth3=1'
driver.get(url)

In [6]:
SCROLL_PAUSE_TIME = 1
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    try:
        driver.find_element_by_css_selector('#dataTable > div.prodListBtn > div.prodListBtn-w > a').click()
    except: pass
    
    for i in range(5):
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(SCROLL_PAUSE_TIME)
    
    new_height = driver.execute_script("return document.body.scrollHeight")

    if new_height == last_height:
        break
    
    last_height = new_height

In [7]:
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')

In [8]:
prodName1=soup.find_all(class_=re.compile('prodName'))[2:]

In [9]:
name_list1=[]
for name in prodName1:
    name_list1.append(name.string)

In [10]:
prodPrice1=soup.find_all(class_=re.compile('prodPrice'))[2:]

In [11]:
price_list1=[]
for price in prodPrice1:
    price_list1.append(price.text[:-1])

In [12]:
df1=pd.DataFrame({'name':name_list1,'price':price_list1,'category':'instant'})

### 과자

In [13]:
driver=webdriver.Chrome('C:/scrap/chromedriver.exe')
driver.implicitly_wait(10)
url='http://cu.bgfretail.com/product/product.do?category=product&depth2=4&depth3=3'
driver.get(url)

In [14]:
SCROLL_PAUSE_TIME = 1
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    try:
        driver.find_element_by_css_selector('#dataTable > div.prodListBtn > div.prodListBtn-w > a').click()
    except: pass
    
    for i in range(5):
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(SCROLL_PAUSE_TIME)
    
    new_height = driver.execute_script("return document.body.scrollHeight")

    if new_height == last_height:
        break
    
    last_height = new_height

In [15]:
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')

In [16]:
prodName2=soup.find_all(class_=re.compile('prodName'))[2:]

In [17]:
name_list2=[]
for name in prodName2:
    name_list2.append(name.string)

In [18]:
prodPrice2=soup.find_all(class_=re.compile('prodPrice'))[2:]

In [19]:
price_list2=[]
for price in prodPrice2:
    price_list2.append(price.text[:-1])

In [20]:
df2=pd.DataFrame({'name':name_list2,'price':price_list2,'category':'snack'})

### 식품

In [21]:
driver=webdriver.Chrome('C:/scrap/chromedriver.exe')
driver.implicitly_wait(10)
url='http://cu.bgfretail.com/product/product.do?category=product&depth2=4&depth3=5'
driver.get(url)

In [22]:
SCROLL_PAUSE_TIME = 1
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    try:
        driver.find_element_by_css_selector('#dataTable > div.prodListBtn > div.prodListBtn-w > a').click()
    except: pass
    
    for i in range(6):
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(SCROLL_PAUSE_TIME)
            
    new_height = driver.execute_script("return document.body.scrollHeight")

    if new_height == last_height:
        break
    
    last_height = new_height

In [23]:
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')

In [24]:
prodName3=soup.find_all(class_=re.compile('prodName'))[2:]

In [25]:
name_list3=[]
for name in prodName3:
    name_list3.append(name.string)

In [26]:
prodPrice3=soup.find_all(class_=re.compile('prodPrice'))[2:]

In [27]:
price_list3=[]
for price in prodPrice3:
    price_list3.append(price.text[:-1])

In [28]:
df3=pd.DataFrame({'name':name_list3,'price':price_list3,'category':'food'})

### 음료

In [29]:
driver=webdriver.Chrome('C:/scrap/chromedriver.exe')
driver.implicitly_wait(10)
url='http://cu.bgfretail.com/product/product.do?category=product&depth2=4&depth3=6'
driver.get(url)

In [30]:
SCROLL_PAUSE_TIME = 1
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    try:
        driver.find_element_by_css_selector('#dataTable > div.prodListBtn > div.prodListBtn-w > a').click()
    except: pass
    
    for i in range(6):
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(SCROLL_PAUSE_TIME)
            
    new_height = driver.execute_script("return document.body.scrollHeight")

    if new_height == last_height:
        break
    
    last_height = new_height

In [31]:
html=driver.page_source
soup=BeautifulSoup(html,'html.parser')

In [32]:
# prodPhoto1=soup.find_all(class_=re.compile('photo'))[2:]

In [33]:
# img_list1=[]
# for img in prodPhoto1:
#     img_list1.append(img.find('img')['src'])

In [34]:
# n=10000
# cnt=1
# for image in img_list1:
#     imgUrl = image
#     try:
#         with urlopen(imgUrl) as f:
#             with open('./prod_img/img' + str(n)+'.jpg','wb') as h: # w - write b - binary
#                 img=f.read()
#                 h.write(img)
#     except: pass
    
#     n+=1
#     cnt+=1
    
#     if cnt > len(img_list1):
#         break

In [35]:
# value = "웅진)하늘보리P340ml.jpg"
# encode = quote(value)
# url = "http://bgf-cu.xcache.kinxcdn.com/product/8801382129608_"+encode

In [36]:
# with open('./prod_img/img' + str(700)+'.jpg','wb') as h:
#     h.write(urlopen(url).read())

# with open('./prod_img/img' + str(701)+'.jpg','wb') as h:
#     h.write(urlopen(img_list[-1]).read())

In [37]:
prodName4=soup.find_all(class_=re.compile('prodName'))[2:]

In [38]:
name_list4=[]
for name in prodName4:
    name_list4.append(name.string)

In [39]:
prodPrice4=soup.find_all(class_=re.compile('prodPrice'))[2:]

In [40]:
price_list4=[]
for price in prodPrice4:
    price_list4.append(price.text[:-1])

In [99]:
df4=pd.DataFrame({'name':name_list4,'price':price_list4,'category':'drink'})

                name  price category
0         마시는식사비건그레인  2,200    drink
1           동아)모닝케어D  5,000    drink
2     HEYROO미네랄워터P1L    900    drink
3            파워마운틴대P  2,900    drink
4    서울)스페셜티마일드250ml  1,900    drink
..               ...    ...      ...
696             솔의눈캔  1,200    drink
697   동서)티오피아메리카노275  2,200    drink
698     롯데)칸타타아메리카노캔  1,300    drink
699    웅진)하늘보리P340ml  1,000    drink
700   가야)알로에농장P340ml  1,000    drink

[701 rows x 3 columns]

## concat

In [106]:
df=pd.concat([df1,df2,df3,df4])
df['qty']=100
df=df[['name','price','qty','category']]
df.index=np.array(range(10864,10864+len(df)))
df.index.name='id_key'

df.name=df.name.str.replace(')','_').str.replace('(','_')
df.price=df.price.str.replace(',','').astype('int')

In [8]:
df

                 name  price  qty category
10864       샌_점보4단햄치킨   2500  100  instant
10865      햄_크림치즈치킨버거   3300  100  instant
10866        햄_빽햄롱롱버거   2900  100  instant
10867      주_빽햄데리마요밥바   1900  100  instant
10868    주_2XL콘햄김치볶음밥   1400  100  instant
...               ...    ...  ...      ...
13980            솔의눈캔   1200  100    drink
13981  동서_티오피아메리카노275   2200  100    drink
13982    롯데_칸타타아메리카노캔   1300  100    drink
13983   웅진_하늘보리P340ml   1000  100    drink
13984  가야_알로에농장P340ml   1000  100    drink

[3121 rows x 4 columns]

In [9]:
df.to_csv('prod_info_data.csv')

## DB 삽입

In [68]:
import pymysql
import pyodbc

In [90]:
mydb = pymysql.connect(
    host = "",
    user = "",
    passwd = "",
    db = "",
    charset=''
)
cursor = mydb.cursor(pymysql.cursors.DictCursor)

In [108]:
for i in range(len(df)):
    sql = 'INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ('+ '"'+ df.name[i]+'"' + ',' + str(df.price[i]) + ',' + str(df.qty[i]) + ',' +'"'+df.category[i]+'"' +');'    
    print(sql)    
    cursor.execute(sql)

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_점보4단햄치킨",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_크림치즈치킨버거",3300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_빽햄롱롱버거",2900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_빽햄데리마요밥바",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL콘햄김치볶음밥",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL소불고기",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_빽햄스페셜정식",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_미트칠리더블버거",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_햄에그샐러드버거",2700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_오븐에구운트리플치킨",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_스키피땅콩버터샌드",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_새떡새떡버거",3400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_돈까스한끼",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_간장찜닭한끼",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_제육한끼",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("핫_브레드이발소시지빵",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_브레드이발소시지김밥",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_브레드소시지삼각",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_브레드쏘야도시락",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_초코윌크브레드",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_남도조기한상",4600,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_확!실한제육김밥",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_확!실한참치김밥",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_확!실한불고기김밥",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("지구인_채식주의샐러드볼",4500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_참치가득유부초밥",3700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_크랩가득유부초밥",3700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_바질페스토두부크럼블",3200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_채식주의콩고기",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("핫_롱앤리치핫도그",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_청양참치마요",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_돼지불고기",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_고추장불고기",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_판타스틱치킨버거",3400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_커리포테이토PLA",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_오븐에구운더블소시지",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL불고기전주",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL참치마요",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_통새우커리덮밥",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_통새우사천짜장덮밥",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_월도프더블스테이크",3200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_크래프트핑크블라썸",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_통새우튀김빅밥바",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_통등심돈까스빅밥바",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_빽햄김치볶음",1100,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_통새우로제닭갈비덮밥",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_갈릭품은햄치즈",2400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_트리플고기정식",4600,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_두껍다!떡갈비김밥",2700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_치킨시저더블스테이크",3200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_치즈갈비찜김밥",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_치즈소고기김밥",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_궁극의정식_불백편",4500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_햄에그치즈샌드PLA",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_허닭훈제닭가슴살",3800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_두툼한통커리치킨버거",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_점보4단햄감자맛살",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_허닭케이준닭가슴살",3800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_허닭오리지널닭가슴살",3800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_두툼한통함박버거",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_트리플치킨강정",8900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_두툼한통돈까스버거",2900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_봄봄햄에그샌드",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_치즈참치마요김밥",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GG_햄치즈브리또",2900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GG_자이언트치킨피자",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_로스트비프볼샐러드",4800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL스팸마요",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_리치전주비빔1",1000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_리치참치비빔",1000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_리치참치마요1",1000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_PLA치킨포테이토샌드",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_그릴치킨아몬드샐러드",4800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_불고기누들볼샐러드",4800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("핫_점보핫도그갈릭디핑",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("핫_점보핫도그미트칠리",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_베스트빅불고기버거",2400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_오븐에구운A1스테이크",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_떡튀순어묵탕SET",6500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_김치제육",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피자_바게트콤비네이션",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_A1스테이크치즈버거",2800,100,"instant");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_A1스테이크치즈샌드",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_참치김치볶음밥",1000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_비프칠리프라이",4000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_통새우플래터",6900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_베이컨맥시멈3단버거",3200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_초코바닐라츄러스샌드",2700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_핫비프칠리샌드",3200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_디럭스스크램블버거",3400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("1입샌드_흑임자",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("1입샌드_햄치즈연유",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("1입샌드_에그포테이토",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("1입샌드_에그코우슬로",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_가라아게불닭덮밥",4000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_통새우유산슬덮밥",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_더블불고기샐러드",5700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_함박&돈까스",4600,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_맥시멈3단버거",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_오븐에구운햄치즈에그",3000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_핫치닭",4900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_풍성한15첩반상",6000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_베스트4단샌드",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_훈제연어왕유부초밥",3900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_큐브베이컨참마",1100,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("간편_베이컨피자떡볶이",5900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_롤유부초밥플래터",9900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_동원고추참치샌드",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_더블골든텐더샐러드",5700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_크랜베리치킨샌드_PLA_",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_피자빵빵버거",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_제육고기쌈",5900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_빼어날수정찬",5900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_서울우유딸기샌드",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_치킨텐더김밥_PLA_",3200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_리챔김치밥버거",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("면_큐브치즈토마토파스타",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("면_파마산크림치즈파스타",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_트리플치즈버거",2700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_크래프트치즈딸기샌드",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_떡갈비＆닭갈비",4500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_참치왕참치마요밥바",1800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("찬_햄치즈듬뿍부대찌개",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_리챔김치볶음밥바",1800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL매콤불고기",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL간장불고기",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_리챔참치마요김밥",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_치즈에그샌드위치",2800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_2XL삼겹볶음",1400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("요리비책_간장닭볶음김밥",2400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_계란떡볶이비빔Ball",2000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("면_나폴리탄파스타",4000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_단짠불고기버거",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_반반치킨",8900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_뉴오세득소이볼샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_뉴오세득터키햄샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_칠리치킨샌드위치_PLA_",3200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_뉴오세득알품닭샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_뉴오세득스파이시치킨",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_흑임자치킨샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_직화고기참피언",4500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_햄이꽉찬샌드위치",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_폭탄전주비빔Ball",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_콰트로타워버거",2700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("요리비책_대파제육정식",4500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_참치마요햄김치볶음",1800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_아임웰푸짐하오리",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_하프앤하프샌드위치",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_광양식불고기",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_햄참치마요",1100,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_참치FLEX",1100,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_에그불고기치즈버거",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_뉴상하이스파이시버거",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_꽃맛살샐러드샌드위치",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_매콤고추장불고기",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_보성녹돈돈까스김밥",2400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_남도떡갈비정식",4500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_딥치즈베이컨버거",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_새우버거",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("요리비책_베이컨땡초김밥",2400,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_오늘은치킨이닭",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("요리비책_길거리토스트",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_반반치킨새우강정",8900,100,"instant");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_이건가요샌드위치_리_",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_강력추천!8찬정식",4500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_딥치즈&치킨미니샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_닭가슴살샐러드170",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_트리플불고기치즈버거",2700,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_속이꽉찬계란샌드위치",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_토핑2배전주비빔",1000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_토핑2배참치마요",1000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_아임닭올리브닭가슴살",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_에그가먼저닭샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_아임닭단백질샐러드",3800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_주먹왕!참치김볶",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_NEW케이준치킨샌드",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_수원식왕갈비치킨버거",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_대만식연유샌드",2000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주_치킨마요삼각김밥",1200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_최애7찬",4000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_햄에그샌드위치",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_백종원7찬매콤불고기",4300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_백종원12찬한판도시락",4000,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_햄참치게맛살샌드위치",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샌_베이컨에그샌드위치",2500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_치킨찹찹샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샐_퀴노아바질샐러드",3500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김_참치불고기반반김밥",2200,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_매콤달콤치즈버거",1500,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("도_고기듬뿍김치제육",3800,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_잇츠빅치즈불고기버거",2300,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("햄_자이언트더블불고기",1900,100,"instant");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("엉덩이탐정_초코카스테라",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("엉덩이탐정_우유카스테라",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤케익초코",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PLA_쫀득한마카롱민트초코",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쁘띠몽쉘샤인머스캣",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_길쭉이보리과자400g",5200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_히츨러소프티바타투",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_LOL스티커색칠북캔디",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤민트초코",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오_오후의티라미수베리",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코스_꿀미니건빵280g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_초코꽈배기페스츄리",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_초코크림단팥빵",1600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_애플모카반반샌드",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_초코렐라66g",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_오트밀미니바이250g",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오그래초코고래30g",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_츄러스쫀득이",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_하리보콜랄라스",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이멕_알토이즈페퍼민트",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이멕_알토이즈스피아민트",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키오땅볼",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_크림치즈쁘띠샌드",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("브레드_딸기소라빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("브레드_땅콩소라빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_브레드머랭젤리초코",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_브레드머랭젤리밀크",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("나무_브레드이발소솜사탕",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("브레드_크래커머랭쿠키",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("브레드_프레첼머랭쿠키",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬깔콘빼빼로1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_하리보피치스",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_하리보피코발라",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키초코바",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_닭다리모양젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에이치비_우유식빵",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유라가_티라미수찰떡꼬치",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_가나슈레이어케익",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_마이쮸포도용기",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_마이쮸딸기용기",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_단짝꿍캔디",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_레틀러즈스윗앤사워",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_저온숙식빵",2600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_땅콩크림빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_옥수수크림빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_뽀로로친구들",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대산_전통강냉이370g",3700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대산_전통뻥튀기180g",3700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_콰삭칩사워어니언",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_콰삭칩트러플솔트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_사과맛카스테라",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_딸기맛카스테라",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오_오후의티라미수녹차",3200,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_촉촉딸기수플레4입",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_다쿠아즈딸기",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_다쿠아즈플레인",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니소보로10입",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키민초볼",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨믹_핑크퐁아기상어젤리",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_로봇의탄생",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_도도한나쵸사워92g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_미쯔볼",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몽쉘솔티피넛케이크",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로투_비스코프샌드바닐라",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로투_비스코프샌드비스코",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_이태리포치즈110",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_미국남부BBQ110g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_얼그레이갸또케이크",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_당근케익초코파이",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_수수깡젤리트로피칼",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_흔한남매냐하젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_그린피스낵60g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_닥터유에너지호두",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_구운짜장",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_매운맛피자빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_이즈니버터스콘",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_이즈니버터와플",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풍림_스위디메이플푸딩",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풍림_스위디초콜릿푸딩",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풍림_스위디밀크푸딩",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_브라우니타르트",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_와클어니언바게트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_프로틴칩스오리지널",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쌀로뻥쿠아즈인절미",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_짜짜로니부셔스낵",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_고향만두칩김치만두",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_고향만두칩고기만두",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨알파촉촉",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨프로폴리스",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서주_비건젤리푸룬맛",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_왓따판박이껌",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("애영_민트초코아몬드볼",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_하리보워터멜론",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_탕종곡물식빵",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_탕종옥수수식빵",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오븐카카오파운드",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신라_옹달잼비스킷8입",6500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤케익그린티",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_쑥라떼찰떡2입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_시크릿쥬쥬롤스티커",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_리콜라애플민트",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_하리보스윗사워베어",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_비달메가줌페인터캔디",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_비달슈퍼팔리피카캔디",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_포카칩지퍼백",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오감자지퍼백",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_꼬북칩지퍼백",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_참오곡크래커",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_도리토스양념치킨맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_커피크로와상",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_봄이왔딸기만쥬",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_아몬드브리오슈",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_명장텐마늘빵",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_소프트땅콩샌드",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_오후의티라미수",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_빈츠카페모카",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬깔콘찰옥수수맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_미니츄러스초코맛",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_목캔디허니민트",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_목캔디엑스트라쿨",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_키커바헤이즐넛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코파이딸기12입",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동화_초코츄러스맛뉴짱",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_유자라불러주오만쥬",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_이즈니버터식빵",2600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬마꿀호떡",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_딸기치즈케익",4800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_딸기티라미수",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PLA_쫀득한마카롱녹차",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_몽키나나젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_스포츠볼젤리",52000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리초코바나나",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로투_록키마운틴마시멜로",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쿨젤리레몬민트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_달콤생도나스",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_녹차청크로얄쿠키",1500,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_초코청크로얄쿠키",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_청포도타르트",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤카페오레",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_카스타드12입",4800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_에이스뉴욕치즈케익",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_생생감자칩레인보우",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오븐에구운호두파이",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_딸기잼맘모스",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_촉촉초코수플레4입",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_다이제건포도비스킷",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_다이제통밀비스킷",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_포테토칩엣지통감자",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_딸기밀크볼",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_락캔디4가지맛",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_닥터유단백질볼",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_폭신딸기케익",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_딸기카스테라롤",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신라_촉촉바삭브루키8입",7900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_촉촉치즈수플레4입",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_허쉬초코쁘띠샌드",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_초록매실젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_아침햇살젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_마이쮸4입케이스",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_파베초코케이크",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_쫀득한마카롱초코5입",6200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_크나버캐쉬",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동화_꿀미니약과525g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_카스타드딸기10입",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몽쉘베리딜리12입",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_허니시몬컵케익6입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니모카크림샌드5입",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니딸기크림샌드5입",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니땅콩크림샌드5입",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_신비아파트드로잉북",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_시크릿쥬쥬비밀편지",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리요후르츠",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서주_흑임자떡모양젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서주_쑥떡모양젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_오잉불짬뽕맛70g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신라_스위트갈릭파이14입",6500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_발사믹블랙포카챠",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_발사믹올리브포카챠",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_초에너지바40g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_촉촉한초코칩16입",4800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_치토스초코츄러스맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬밀크덧",2800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬너겟요거트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬너겟스트로베리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_티피크리스피",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_티피오리지날",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PLA_쫀득한마카롱초코",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PLA_쫀득한마카롱딸기",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PLA_쫀득한마카롱3입",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유라가_흑임자찰떡꼬치",2800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_그래놀라현미310g",6900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_그래놀라크랜베리350",6900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_찰초코파이앙크림",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오웨하스화이트",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오웨하스초코",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("엠탑_서울우유바나나젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("엠탑_서울우유딸기젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_ABC초코쿠키핑크베리",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_초코소보로패스츄리",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_슈크림패스츄리",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_플레인치즈타르트",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_크래프트휘낭시에",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_끼리치즈카스테라",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칙촉브라우니컵",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_딸기패스츄리15입",7900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_땅콩소보루스틱5입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_하양송이",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코파이쇼콜라",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_후르츠텔라딸기",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_후르트텔라오렌지",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_트윅스탑10입",4500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_우유앙빵3입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_말랑말랑우유찰떡",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_깔라만시컵케익",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_쫀득한두꺼비마카롱",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_래핑카우치즈케익",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_래핑카우씨앗호떡",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_래핑카우치즈샌드",1800,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("새롬_큐브브레드슈크림",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("새롬_큐브브레드초코",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO메론우유맛스낵",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO바나나우유맛스낵",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_이클립스소프트레몬",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_이클립스소프트민트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_스니커즈크리스퍼",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뚜또_파인애플250g",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_맛있소순우유케이크",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_리얼생초코찰떡2입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("티디_생미쉘초코칩마들렝",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("티디_생미쉘마들렝",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_맥비티투고다크초코",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_수수깡젤리버블껌140g",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리젖소모양젤리",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쇼콜라카스테라",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_구운찰떡초코",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_구운찰떡플레인",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_허쉬구운도넛10입",9900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_샹달프그레인브레드",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_샹달프허브브레드",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬쿠앤크프레첼",6500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬밀크초코프레첼",6500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_감튀레드칠리맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_마이구미잼",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("몽뜨_아폴로",700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_제주녹차롤케익",4500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_딸기티라미수",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_호두파이",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_딸기찰떡",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬미스터굿바",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("트레마리아_초코칩웨하스",1400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_모나카상점흑임자",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_모나카상점통팥",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_임자있는찰떡쿠키",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_쑥쓰러운찰떡쿠키",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤케익딸기",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨믹스_핑크퐁상어가족",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_LOL에그빈",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_킷캣팝스",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_퀘이커오트바카카오",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몬스터칙촉쿠앤크",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_베이크드케틀콘칩70g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_도리토스비츠머쉬룸",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_양갱상점스위트",2300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_양갱상점클래식",2300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_딸기초코케익",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_생크림딸기잼케익",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_스트로베리치즈케익",4800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_킨더부에노",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_원조고소미1979",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_신짱씨앗호떡맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_허쉬초코포켓샌드2입",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_체리초코케익",5500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_푸딩카스테라딸기",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_푸딩카스테라바닐라",2600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_밀카레오",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_LED불빛반지캔디",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_빅롤리팝버블껌",300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_속깊은맘쿠키",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬초콜릿모찌쿠키",5500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_까망칸쵸바닐라맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_초코츄러스맛팝콘",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_맛동산블랙아몬드90g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_빵빵초코크림빵",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_쫀득한초콜릿마카롱",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_츄파춥스피즈캔디",300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나랑드샤쿠키",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_마켓오빵둥이96g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키팝콘55g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_에어베이크드4번들",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_히말라야체다치즈",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_히말라야사워어니언",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_히말라야오리지널",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_인절미크로와상",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_흑임자파운드",2800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나티라미수",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_크리스마스마카롱",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신세계_레드벨벳케이크",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_고스트칠리페퍼칩",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_밀카칩스아호이",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유라가_고구마찰떡꼬치",2800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신세계_우유케이크",3200,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키카카오스낵볼",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신세계_리코타치즈케이크",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬민트크림샌드",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_옥수수깡70g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서주_삼육두유웨하스63g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오븐생크림도넛10입",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("ABC초코쿠키쿠앤크",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_빅카초",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_리세스투컵스",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_킷캣청키팝콘",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_더블크런치쿠앤크",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_바로그대로호떡",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_미니보름달2입",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_스노우찰떡2입",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤케익순우유",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_하리보해피콜라사워",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_왓따가나풍선껌",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매크로_자케미니브라우니",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_한입그래놀라치즈",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_한입그래놀라갈릭",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_숯불갈비왕호빵",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_동글동글빵카롱",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_20피자호빵_1입_",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_20야채호빵_1입_",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_인절미빼빼로1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬쿠키초코칩베리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_밀크초코바나나킥",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_요미미니팝트리치즈",3900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_요미쌀떡뻥사과당근",3900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤케익두유",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙_야미얼스유기농롤리팝",3600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_20통단팥호빵_1입_",1100,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_빵빵딸기크림빵",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_빵빵우유크림빵",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_박카스사워젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대두_이밤의끝을잡고만쥬",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_불빛요요별사탕",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_얼초공룡만들기",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_스타케익요거트애플",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_디저뜨와치즈케이크",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_디저뜨와브라우니",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_리츠초코샌드77g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_스위트칠리110g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_빵판다쌀쉬폰케이크",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_부드러운단팥왕호빵",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_고기부추왕호빵",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나다크밀크",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로투스_비스코프1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_짱구115g",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_콘칲골드",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO크림맛팝콘",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_우유카스테라",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_먹는색종이과일ICE",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_먹는색종이딸기맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬다크볼아사이",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬다크볼석류",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_프루팁스자몽30g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_프루팁스레몬30g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬_프루팁스오리지널30g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_알라딘팔찌캔디",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_리콜라크랜베리",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_참쌀선과",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_참쌀설병",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쁘띠몽쉘레몬그린티",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쁘띠몽쉘커스카라멜",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_꿀땅콩카라멜콘900",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_구운대파",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유라가_앙버터쑥떡",2600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유라가_앙버터찰떡",2600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리베리향100g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리키스",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_고래밥볶음양념800",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_허니버터칩프로마쥬",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_마이구미청포도맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_히츨러수수깡젤리",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오레오_밀크스낵_냉장_",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매크로_하이츄파인애플맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_애플뚱모스빵",2800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쿠키브라우니케이크",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_메가푸쉬팝",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_사브레1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_후룻바틀망고666g",7000,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_크림치즈휘낭시에8입",7900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_크림치즈케익빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_눈을감자케이준",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_칸츄리콘90g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("주사위팝33g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리샤크젤리100g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_사워글로웜즈100g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_바나나케이크",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_조안나팝콘",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO크림어니언감자칩",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO오리지널감자칩",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO콘칩매콤달콤한맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_워터젤리파인애플130ml",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_워터젤리복숭아130ml",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마카롱모양젤리28g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_얼초보석만들기",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유라가_초코찰떡꼬치",2800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_큐브크림치즈케익",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_첵스바오리지날25g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오뜨치즈6입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오뜨쇼콜라6입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("ZOTT_몬테스낵_냉장케익_",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아몬드초코볼46g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_야채타임70g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_포테토칩에그토스트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("끼리냉동_딸기치즈찰떡",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("끼리냉동_베이크치즈찰떡",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_쫀득한아이스마카롱",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_더블쇼콜라타르트",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_사워꿈틀이67g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_감자톡매콤달콤80g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_감자톡허브솔트80g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_쿠키티라미수",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_쇼콜라티라미수",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아띠_반두아코코넛델리",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_멜로빅머쉬멜로우",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_쿵떡쿵떡흑임자",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_쑥떡쑥떡인절미",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_티라미수초코파이",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_레드벨벳초코파이",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코파이오리지널",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대영_아몬드초코볼",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_다이제볼42g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬깔콘치먹스파이시",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_애플크럼쿠키",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_쁘띠샌드트리오6입",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_미니초코쿠키1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_미니아몬드쿠키1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨빅팩껌",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_하리보골드바렌12g",300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미찌_곰표나쵸오리지널맛",2300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("모리_맛차카라멜58g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_유칼립톨캔디30g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨마우스워터",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몬스터마가렛트애플",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_구운휘낭시에8입",5900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오븐에구운도넛10입",6900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_후룻바틀파인애플666g",7000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_후룻바틀황도666g",7000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이멕스_비첸지초코크림65g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이멕스_비첸지밀크크림65g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_감자속감자버터맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_크림치즈호두단팥빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_통밤단팥빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_초하스화이트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_초하스초코",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_BIG에그짱2보이",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_팝핑캔디스낵초코맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_작아도달고나25g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO더블카라멜팝콘컵",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_카카오쿠키볼58g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_졸음번쩍껌87g",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_예감볶은양파1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸쵸컵95g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키빼빼로1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_크리미쉬림프110",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오감자찍먹바베큐",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_후레쉬베리6P",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_김을만난라이스칩",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_냉동갈릭소시지빵",8000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_냉동미니크로와상",7000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_호박쫀드기84g",1500,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_옥수수쫀드기84g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_맛기차콘84g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_삼거리캔디21g",400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코코_단짝캔디46g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("큐피트_꾀돌이48g",700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("큐피트_밭두렁45g",700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키딸기바나나",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_디샤민트스타38g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_포스트코코볼300g",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_아몬드후레이크300g",5800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_치즈뿌린치킨팝",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_핫스파이시53g",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오곡코코볼바",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_콘딸바",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핵짱셔요후르츠",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핵짱셔요콜라",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_두조각심플케이크",3700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_큐브티라미수",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬후퍼스49g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_그래놀라바카카오",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_오예스쿠앤크6000",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_미니웨하스딸기맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_미니웨하스바닐라",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_츄파춥스서프라이즈",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_젤리벨리풍선껌향",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("청우_쫀득초코칩90g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_프루팁스트로피칼",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_더탱글마이구미",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_하리보메가룰렛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나마일드볼",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬미니바밀크",600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬미니바쿠앤크",600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_몰티져스다크싱글37g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO하늘의별딸기",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_쫀득한딸기마카롱",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_돌아온배배80g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서석_투바이트브라우니",2600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_사또밥67g",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("실속_2000버터크로와상6입",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_누드빼빼로1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_대왕젤리밥65g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_쫀득찰떡쿠키",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_초코카스테라롤",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_몰티져스밀크사각90g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("몰티져스밀크37g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("고려_고려은단",4500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("청우_찰떡쿠키오리지널",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_프레첼솔티카라멜맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_고구마깡1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("여리수_UFO에스파피어과자",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_UFO캔디10g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_프루팁스리치140g",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_홀스자몽34g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_초단백질바50g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아띠_댄케이크버터쿠키18g",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_죠리퐁마시멜로900",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서주_허쉬민트웨하스63g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_꼬북칩달콩인절미",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유라가_조청인절미꼬치",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오레드벨벳94g",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조이_쫀득한마카롱3입",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_하리보그레이프",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서주_허쉬초코웨하스63g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("SCD_UFO캔디75g",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼광_아몬드바크씬",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼광_마카다미아쇼콜라",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_하리보사우어룰렛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_브라운슈가버블젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_하리보사우어웜즈",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬초코크림샌드",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_미니허쉬쿠키",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("참조은_쫀득롤케익플레인",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("실속_1500모닝롤6입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("실속_1500식빵10입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("흥양_빵빵덕레몬젤리",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_마켓오브라우니6P",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_고소미1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("델푸드_블럭젤리",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키볼1000",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_거꾸로초코블랑",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_국희땅콩샌드",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_프로틴바30g",1400,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_첵스초코230g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("끼리냉동_블루베리치즈케",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_추억의옛날롤케익",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_초코시루케이크",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_예감치즈그라1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_예감오리지널1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_베이비팝스윗사우어",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_쿠키크림케익",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_눈을감자오지치즈",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_바비카메라캔디",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_더블미니파운드",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_쫄깃한찹쌀떡",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_대박찹쌀떡",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("징코_폭신크림카스테라",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_치토스매콤달콤_대_",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쌀로별오리지널_대_",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_새콤달콤레몬볼",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아이스캔디파우치",9900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_아이셔팝캔디",200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_감자품격트러플",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아미카_엘도라다감자칩400",9900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아이스브레이커딸기",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_얼초동물그리기",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오븐에구운도넛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬카카오파이6입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_태양의맛썬바게트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미찌_곰표팝콘오리지널맛",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_수박바젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립미각_카스테라롤",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_무지개케이크",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_마늘감자맛110g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_포테토칩육개장사발",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_다이제씬",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_초코소라빵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_별뽀빠이72g",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리버거XXL",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_ABC초코쿠키50g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_포키1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키바월드콘맛",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_아카시아껌1000",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_은단껌1000",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_꼬북칩콘스프160g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_태양의맛썬135g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_쿠앤크오믈렛",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_닥터유단백질바",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_쫄병짜파게티맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_감자소스데리야끼",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_크런치넛에너지바",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_치킨팝닭강정맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_청포도젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_포키체리블라썸",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_페레로누텔라앤고",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_콘푸로스트컵",1600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_ID믹스베리껌",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("끼리냉동_스틱치즈케익",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_티라미수홈런볼46g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("리얼딸기초코볼",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_에스키모밥60g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_꿀땅콩듬뿍카라멜",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_빅딸기샌드2입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO리틀치즈큐브",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("델리팜_앤디스토피크런치",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("델리팜_앤디스민트초콜릿",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_벨기에초코와플",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_초코블랑",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_든든왕만쥬",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_엄마손파이127g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_꿀데니쉬4입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매크로_하이츄사워레몬맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_크림치즈시나몬롤",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_킷캣청키쿠앤크",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_박카스젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_리필오리지널껌",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("예스_트롤리미니버거10g",400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("피오레_우유생크림케익",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_빠새콘치즈랍스터맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_생크림파이6입",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키바돼지바맛",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_도리토스나쵸치즈",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_파인애플컵198g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼광_마카다미아미니초콜",600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_꽃게랑",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_구미구미젤리",1000,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_포키극세",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_밀카오레오",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_밀카알파인밀크",2900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_감자엔소스칠리맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_스니커즈다크",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_그래놀라바검은콩",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_그래놀라바무화과",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_이클립스피치캔디",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_이클립스페퍼민트",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_코팅자일리톨빅팩껌",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_하리보자몽맛100g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_오사쯔1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_칼로리바란스",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니연유샌드5입",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬깔콘군옥수수144g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몬스터칙촉티라미수",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몬스터칙촉쇼콜라",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_저온숙성밀키팡",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO고구마스낵1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO마늘맛콘스낵1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO오란다스낵1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO왕소라과자1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_잼있는딸기쿠키",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_잼있는사과쿠키",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_애니타임봉지캔디92g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_스카치봉지캔디157g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_청포도봉지캔디153g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_아이셔츄잉청사과",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO까망베르쿠키1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_구운치즈감자칩",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO김두부스낵",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO진한초코칩쿠키",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_오예스6000",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_땅콩카라멜봉지",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_닥터유에너지바",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_화이트쿠키빼빼로1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아몬드빼빼로1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_초코빼빼로1500",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_딸기웨하스900",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_크림웨하스900",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_맛동산90g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_자유시간아몬드36g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_연유요팡",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO쌀떡볶이1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO신나는뉴짱1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO달콤한대롱과자1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO꼬불이라면스낵1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO뻥이요스낵1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_푸쉬팝트리플캔디",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO간장치킨맛팝콘1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_오징어다리달달구이",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO카라멜맛팝콘1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO고소한치즈팝콘1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO콘소메맛팝콘1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_후라보노쿨민트",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_콘푸로스트230g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쌀로별오리지널",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오오즈250g",6100,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_키커바트윈딸기맛",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_새콤달콤블루소다",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_태양의맛썬80g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_쁘띠첼포도160g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_쁘띠첼복숭아160g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬밀크초콜릿",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_푸쉬팝캔디",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_씨리얼오트컵",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_젤리데이석류",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_자유시간크리스피",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_쁘띠첼밀감160g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_미니쉘딸기24g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_킨더조이뽀로로",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_허쉬초코시리얼50g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아이스브레이커포도",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_콘푸라이트밀크바",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_쫄병안성탕면맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코칩초코파이",6000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_키커바녹차맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_홀스XS레몬민트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_홀스XS멘토립터스",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_카라멜오리지널",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_통크",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_웰치스후르트젤리",1600,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("켈로그_첵스초코컵",1600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_다이제미니초코",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_저온숙성완듀팡",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팝콘_렌지용팝콘버터맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_할라피뇨110g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬쿠키화이트",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬쿠키오리지널",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_콘푸라이트",4100,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_새우깡90g",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_허니버터칩",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬깔콘군옥수수맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬깔콘매콤달콤",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_꿀꽈배기90g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_포카칩어니언66g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_닭다리너겟130g",2700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_매운새우깡90g",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_포카칩오리지널66g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_포스틱84g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_초코홈런볼46g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코파이12입",4800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_빈츠",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_초코홈런볼146g",4500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마가렛트264g",4400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_다이제초코",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸쵸54g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_맛동산165g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO콘초코플러스",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_양파링84g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_콘칩70g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO소프트인절미스낵",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_쫄병매콤한맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_오징어집83g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오징어땅콩98g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오징어땅콩202g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_자갈치90g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_에이스",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코송이",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오화이트크림",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해광_프레첼체다치즈",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몽쉘카카오케이크6입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_카스타드6입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_제크오리지널100g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_꼬깔콘고소한맛67g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_허니버터칩120g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO맛새우칩",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_바나나킥75g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_스윙칩고추장60g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_오리지널110g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO마늘바게트",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_촉촉한초코칩",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_빠다코코낫100g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칙촉",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오초콜릿크림",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_버터와플",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_몽쉘크림케이크6입",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_닭다리후라이드66g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_고소미",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_스윙칩사워어니언",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO콘칩군옥수수맛170g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_치토스매콤달콤한맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_양파110g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_콘초",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_도도한나쵸치즈92g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_양파맛53g",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_눈을감자56g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO프레첼&카라멜",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_땅콩강정",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_쿠크다스128g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코칩쿠키",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로아카_카카오웨하스",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_초코픽",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_빅파이딸기",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_쵸코하임142g",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_롯데샌드오리지날105",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_미쯔스낵팩",700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_뿌셔뿌셔불고기맛",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_꼬북칩콘스프맛",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_카라멜콘메이플74g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_조청유과96g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_핫스파이시110g",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_포카칩오리지널137",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("초코_포켓몬스낵",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프링글스_오리지날53g",1700,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("청우_참깨스틱",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_참붕어빵6입",4200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_버터링쿠키",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_리츠치즈샌드96g",1900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_구운감자",3600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_오감자그라탕50g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_알새우칩68g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO체다치즈나쵸칩",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_죠리퐁",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_치토스스모키바베큐",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_왕고래밥스낵",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("초코_신짱초코비",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_후렌치파이딸기",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_화이트하임142g",3300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_다이제",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로아카_바닐라웨하스125g",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_인기스낵4번들",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_포테토칩60g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO계란과자1200",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_못말리는신짱",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로아카_바닐라웨하스",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_참크래커",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_뽀로로친구들치즈",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_산도딸기",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_포카칩어니언137g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_무뚝뚝감자칩",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_츄러스84g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_구운양파",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코파이2P",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로아카_에스프레소110g",3800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_예감치즈그라탕80g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오씬즈바닐라",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오레오씬즈티라미수",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_감자깡75g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_카라멜콘땅콩56g",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_리츠크래커80g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_초코파이",400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해광_프레첼갈릭버터",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_에그카스테라",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드냉장_크림가득메론빵",1600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_뉴땅콩샌드",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_뜯어먹는밤빵",1600,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_뉴혼당패스트리",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_초코반달케이크",1400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_카스타드듬뿍빵",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_초코크림크런치",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_단팥듬뿍빵",1100,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_망고컵198g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_복숭아피치컵198g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뚜또_후르츠믹스250g",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뚜또_코코딸기250g",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뚜또_밀감250g",2400,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니딸기샌드",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니땅콩샌드",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_콜드브루롤케익",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_빅스위트데니쉬",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_주종카스타드단팥빵",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_주종단팥크림빵",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_한아름밤만쥬",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_우유식빵",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_촉촉밀크후레쉬팡",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_촉촉치즈후레쉬팡",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_신선꿀호떡",1900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_정통크림빵",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_정통보름달",1300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_허니카스테라",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_미니약과",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_롱패스츄리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_워터젤리복숭아170ML",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_워터젤리사과170ML",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로투스_초코와플",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로투스_오리지널와플",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_왕꿈틀이1000",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_죠스바젤리",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_마이구미포도1000",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("트롤리_스파게티딸기젤리",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로아커_화이트초콜릿50g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_미니쉘아몬드24g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("로아커_다크노아초콜릿50g",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_더자일리톨용기껌",4000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_킨더초콜릿맥시",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_쥬시드랍팝캔디",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_페레로로쉐5구",3400,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대영_졸음뚝용기껌",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_츄파춥스게코젤리",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_키세스쿠앤크82g",3200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_목캔디믹스베리",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_목캔디허브",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_밀크카라멜50g",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_ID자일리톨화이트껌",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하리보트로피프룻100g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_키세스쿠앤크52g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_키세스아몬드52g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_키세스밀크52g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_드림카카오72%",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_워터젤리포도170ml",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_프루팁스젤리",2200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_후룻바이더풋젤리",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_홀스블루베리",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하리보스타믹스100g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_킨더초콜릿4입",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하리보프루티부시100g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_킨더초콜릿조이걸",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_킨더초콜릿조이보이",1700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_새콤달콤포도",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키더블크런치바",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_스니커즈땅콩",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_트윅스쿠키",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_비틀즈캔디",700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하리보해피콜라100g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_트윅스쿠키4바",1900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_후라보노레이디",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_후라보노오리지널",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_아카시아껌",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_은단껌",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_스니커즈픽앤믹스",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_홀스레몬맛",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나마일드초콜릿70g",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나밀크초콜릿",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하리보골드바렌100g",1800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬아몬드초콜릿",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나초코바아몬드",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬쿠앤크초콜릿",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_통아몬드캔디",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_마이쮸포도",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_마이쮸복숭아",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_마이쮸사과",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_마이쮸딸기",800,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_베이비팝캔디",2500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_와우소다풍선껌",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_킷캣4핑거초콜릿",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_킷캣청키초콜릿",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아이스브레이커베리",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_토블론밀크초콜릿35g",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일신_리콜라허브레몬",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_왓따콜라풍선껌",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_새콤달콤레모네이드",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_왓따복숭아풍선껌",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_엠앤엠피넛초콜릿",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_엠앤엠밀크초콜릿",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_연양갱",900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_페레로로쉐3구",2100,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_스피아민트스틱팩껌",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_쥬시후레쉬스틱팩껌",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨W껌",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("경남_레모나산10입",3500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_키커바",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_트윅스미니초콜릿",300,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸쉬팝캔디",1200,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_자유시간초콜릿바",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_핫브레이크",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아라비카커피껌",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_ABC밀크초콜릿",2000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나마일드초콜릿34g",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_스키틀즈사워캔디",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_츄파춥스",250,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_멘토스레인보우",700,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_크런키초콜릿",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_홀스멘토립터스",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서영_홀스아이스블루",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨F빅팩",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_스니커즈헤이즐넛",1900,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_이브로즈껌",1000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨용기껌87g",5000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_자일리톨용기껌52g",3000,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_가나초코바땅콩",1000,100,"snack");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_허쉬쿠키초콜릿",1500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("크라운_새콤달콤복숭아",500,100,"snack");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_돈규볶음밀키트",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_돈규라이스",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("영찬_치즈앤미트스키니",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_맛있는라면비건",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("KKMC_골드키위1입",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("KKMC_골드키위900g",10500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_세척꼬마참외1입",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_못난이반값참외5~6입",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_허니버터아몬드130g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_와사비맛아몬드130g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("성경_김갑생할머니김",600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_궁물즈짜장볶이",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_궁물즈라볶이",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("위드고_민트비치10T",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_민트초코라떼8T",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_다시다멸치디포리",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_스팸라이트200g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_한입연어스테이크",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_후르츠베어도시락",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진진_강릉커피라떼8T",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아라움_찐오징어튀김땡초",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_도가니탕460g",6400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_소머리곰탕460g",6400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_쌀떡국용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반BIG스팸김치덮밥",5400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반BIG치킨마요덮밥",5400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반BIG스팸김치덮밥",5400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_시원한냉우동컵",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_쿡탐고기곰탕면컵",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_쿡탐육개장면컵",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_쿡탐부대찌개면컵",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_크리미포션치즈",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_올리브포션치즈",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_미정당쫄면볶이",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_고향만두김치가득",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사세_콰트로치즈치킨칩",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PSK_큐티만다린10~12입",9000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("우양_점보모짜핫도그",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_부산매운어묵라면컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO라면득템5입",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_치즈폭발BIG후랑크",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_육즙폭발BIG후랑크",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이오_비건육포스파이시",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이오_비건육포오리지널",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("만전_한포김자반스틱",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_스팸매콤덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_치즈쏙크라비아",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동의구운란2입X주호민",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_매콤크림리조또",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_치킨크림리조또",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고배추김치100g",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_두부크럼블카파오",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_두부크럼블짜장",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_대파불고기간장200",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_대파불고기고추장200",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_콩박스테이크밀키트",9500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_콩박스테이크220g",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("디엔비_점보콘치즈피자빵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오븐감자고로케",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오븐피자고로케",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_고추참치마요덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_동원참치마요덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_군옥수수아몬드130g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_부드러운모카20T",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_직화구이BIG후랑크",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_불닭크림떡볶이양념",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_필라델피아크림치즈",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_투움바파스타",3600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_고단백두부바",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_바른어묵해물280g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_바른어묵야채280g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GG_고구마콘치즈브리또",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김선생_로제가락떡볶이",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_직화로구운곱껍",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_직화로구운두껍",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥팔보채덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥XO게살덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마시는오트밀옥수수",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_쌀컵케이크바나나",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_쌀컵케이크치즈",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_깐메추리알90g",1700,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_체다치즈3입",990,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_인포켓스낵치즈체다",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_통계란샐러드고구마",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_통계란샐러드콘감자",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("만인산_매운고추200g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("만인산_오이맛고추250g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("만인산_추부깻잎5묶음",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("만인산_상추깻잎모듬팩",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("만인산_쌈장미니모듬쌈",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("만인산_대파반단",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("델몬트_조각과일믹스180g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_무지개방토컵",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_시원한두껍라면컵",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_돈스BIG닭다리",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("천일_골목반점볶음짬뽕",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("천일_골목반점옛날짜장",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_가맥소스쥐포구이",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_해찬들고추장200g",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_피자치즈팡50g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HJF_슬라이스닭가슴살그릴",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HJF_슬라이스닭가슴살페퍼",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("새롬_썬키스트오렌지3입망",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_매생이크림떡볶이2인",10500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_매생이크림떡볶이",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_롱줄면짜장컵",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_힐러고기짬뽕컵",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_경규옹순대국면",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_경규옹돼지국밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_신당동떡볶이양념",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_부산고등어조림양념",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에스디_어묵탕매운맛",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에스디_어묵탕순한맛",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_대구쇠고기육개장",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_마포차돌된장찌개",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("상도_BIG직화스파이시치킨",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("상도_BIG직화스모크치킨",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_더킹볼케이노70g",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_반숙계란장160g",2600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진진_강릉커피블랙8T",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("G7_블랙커피100T",12000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_배홍동비빔면",1050,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_불향짜장볶음면",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_매콤닭갈비볶음면",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_안동찜닭양념",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_춘천닭갈비양념",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("테일러팜스_건자두50g",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신화_빼빼오오징어빨간맛",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_지파이180g",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_어피치핫도그70g",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_무지핫도그130g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마니커_한마리옛날통닭",9900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉직화꼬치바청양",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_매콤참치마요덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이_귤먹은여우티5T",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_꽁치300g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_밥도둑돼지장조림",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마니커_바사삭치킨한마리",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_육즙가득부어스트",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살바할라피뇨",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_오색리조또밀키트",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_대저토마토500g",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_청적포도믹스컵",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_맛있는라면",1100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_나가사끼짬뽕",1100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_메밀소바",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_번데기130g",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_치즈불닭210g",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에쓰푸드_킬바사비엔나",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아라움_땡초간장치킨",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아라움_허니갈릭치킨",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_오지치즈찍먹소스",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_맵닭치즈찍먹소스",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO우리쌀밥6입",5940,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_꽃게랑면컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_쌀국수소고기장국",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집열무김치80g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_진종합어묵230g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("흥생_구운계란10입",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("흥생_반숙계란3입",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한만두_구운김치왕교자",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한만두_구운고기왕교자",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살바갈릭",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칠갑_똑쌀떡국얼큰",2500,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칠갑_들깨수제비",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_닭가슴살곤약죽",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_매콤닭가슴곤약죽",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_순수한밥210g",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_밥도둑메추리장조림",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_밥도둑멸치볶음",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_옛날사골곰탕죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_옛날도가니탕죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_고들빼기두루치기",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_입맛리턴고들치기",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_양념치킨뿌렸닭",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뉴자이언트_왓더맵떡볶이",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이디야_골드블렌드20T",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이디야_모카블렌드20T",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마시는오트밀딸기",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_떡볶이소스볶음밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_중화식짜장볶음밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뉴트리_비비랩콜라겐3입",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유성_유동뚝배기번데기탕",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신세계_깐풍닭강정400g",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_사천깐풍뿌렸닭",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에이치앤비_씨없는적포도",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에이치앤비_씨없는청포도",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("더본_빽햄200g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야도가니스지",6400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_베지가든매운떡볶이",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_베지가든짜장떡볶이",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_김치크림볶음밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_스팸간장덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_짬뽕어묵탕밀키트",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_오징어짬뽕어묵바",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_몽글몽글컵누룽지",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_신한생면튀김우동",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_구운전갱이고추장",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_메추리알장조림",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_돼지고기장조림",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_다담된장찌개양념140g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_다담강된장양념140g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_다담순두부양념140g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신세계_찹쌀꿔바로우400g",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_에어프라이어치킨",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고컵만둣국160G",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뉴자이언트_순대떡볶이",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팜덕_흑마늘훈제삼겹400g",10900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팜덕_허브갈릭훈제오리400",10900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에스피_사파이어키위번들",7500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에스피_사파이어키위4입팩",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_디카페인미니10T",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_오징어와사비마요",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_노가리와가맥소스",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반간장계란장덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반참치마요덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_매운양념소대창",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_소금구이소대창",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살소시지훈제",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살소시지일반",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_해물짬뽕떡볶이",3400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PSK_프리미엄체리400g",8500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_아삭숙주300g",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_한끼연두부유자",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_키위샐러드소스115g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_오곡참깨드레싱105g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_오리엔탈드레싱105g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_치킨너겟300G",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이_100%꿀꺽스틱",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_삼양라면골드컵",1350,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_치즈소불고기195g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_크림찹소테이크190g",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에쓰푸드_존쿡킬바사270g",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_바로먹는햄등심140g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_불닭소스스틱",500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_보글보글된장라면컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프레_시카고레드스테이크",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("프레_뉴욕스트립스테이크",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_미니윈너280g",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_콤비부어스트파티330",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한만두_새우샤오롱바오",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_크라비아90g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_이즈니포션버터80g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_베지가든떡국",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_마늘빵아몬드40g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_청양마요아몬드40g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_카라멜아몬드40g",2000,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_인절미아몬드40g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_군옥수수아몬드40g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_와사비맛아몬드40g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_쿠키앤크림아몬드40g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_허니버터아몬드40g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("리챔200g*3+1입",10900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_참치100g*3입",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_파스타소스기획",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야소막창260g",12000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_소가순두부350g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에이치앤비_체리200g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_과일뱅쇼키트",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_매콤순살닭볶음탕",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_통그릴델리햄150g",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_트러플델리햄260g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_극한직화후랑크청양",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_극한직화후랑크치즈",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("꽃샘_리얼민트핫초코원컵",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반육개장국밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반황태국밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_맥반석구이오징어",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_질러빠다갈릭쓰30g",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_수육삼겹족발SET",11900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("큐원_비스킷호떡믹스기획",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_폰타나포테이토수프",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_폰타나머쉬룸수프",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면두부김치",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_얼큰굴탕면",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_속이꽉찬후랑크180g",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마니커_통다리더골드",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_빨간밥키트2인분",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_빨간밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_크림진짬뽕",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_사골굴떡국",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_각잡다핫바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_마일드미니150T",29000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙_직화껍&닭",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_소스에꼬쳐바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고고등어구이60g",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고가자미구이70g",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양사_큐원팬케익믹스",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양사_큐원와플믹스",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_수라우거지감자탕460",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_수라도가니설렁탕460",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO우거지된장국",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO육개장",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("공덕_꿀고구마2입",3400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_직화구이나눠바",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("보승_뽀얀사골수육곰탕",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("보승_뽀얀사골순대국",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("맥널티_제주말차라떼원컵",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_멸치칼국수",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_씻어나온잡곡2kg",14800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_씻어나온백미2kg",17800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_핸디피자핫치킨",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_핸디피자고구마",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마니커_통다리더블랙",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_복돼지면",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_스위트콘340g",2400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_질러빠다콘쓰30g",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_통통하게맛살",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_화끈국물불닭발",7500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_양념새꼬막50g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_진미채조림50g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_소세지야채볶음70g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO육개장칼국수",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO멸치칼국수",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_희망줄라면컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("흥생_반숙계란2입",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("흥생_반숙계란1입",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_메추리알장조림120g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_쫄깃무말랭이120g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_양념깻잎120g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("커피빈_헤이즐넛아메5T",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_1일1봉캐슈넛25g",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_1일1봉호두25g",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("녹차원_인절미라떼원컵",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("녹차원_흑임자라떼원컵",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("종_락토핏유산균데일리",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥수원식갈비탕",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥된장짜글이",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("보승_한판수육&무김치",8500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("흥생_품절대란15입",5000,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_단감3입",3600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살훈제",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("맥널티_고구마라떼원컵",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("할리스_바닐라딜라이트10T",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_1일1봉아몬드25g",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_1일1봉믹스너트25g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO미역국",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO계란국",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO미소된장국",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_사리곰탕면",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_너구리순한",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_각잡다후랑크",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_뚱한치즈메가돈스바",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_뚱한메가돈스바",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살샐러드훈제",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살밀샐러드",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("G7_블랙커피15T",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_사천마라훠거탕면컵",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_사천왕마라탕면컵",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("현대_갈릭페스츄리오징어",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("현대_BBQ페스츄리오징어",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코주부_의성마늘육포40g",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO어니언스프",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO양송이스프",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO콘스프",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_곱창철판볶음밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("장충동_큐브순살매운족발",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("장충동_중화식동파육",7200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("고래사_프리미엄컵어묵탕",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_얼큰유부우동컵",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_가쓰오우동컵",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_돼지고기김치볶음",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_반반한불고기300g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_반반한닭갈비300g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_달콤누들떡볶이",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_참치마요데리덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_핸디피자콤비네이션",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_핸디피자불고기",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한만두_구운샤오롱바오",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HJF_매콤숯불목살구이",6200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HJF_숯향가득삼겹살구이",6200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_하몽슬라이스",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_반모두부기획팩300g",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_부산어묵200g",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이디야_토피넛라떼6T",3600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이디야_아메리카노10T",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_짜짜로니",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_보노체다치즈컵스프",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_보노콘컵스프",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반매일찰잡곡밥210g",2650,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반매일오곡밥210g",2650,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_매콤불고기덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_광양식불고기덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뉴자이언트_계란떡볶이",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_멜론망고치즈",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_살구아몬드치즈",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_고당도하우스감귤500",8000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_칼칼한어묵리카노",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_시원한어묵리카노",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집볶음김치80g",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_치킨무100g",500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_순살치킨스테이크",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_매콤닭오돌뼈볶음",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_불닭소시지",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_핵불닭발",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_9900질러육포세트",9900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_모둠견과플래터",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_크림불닭볶음면컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집맛김치80g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_매콤곱창편육볶음",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_아라비아따파스타",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_만두사리김치맛",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_밥도둑불닭볶음",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_밥도둑땡초장조림",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_크림진짬뽕컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("디앤_쟌슨빌스모크6입",9200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_랍스터킹128g",3100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("델몬트_파인스틱90g",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_오감칠리소시지",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_오감새우감바스",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_스낵면",650,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("더리얼_소고기그레인프리",4400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면블랙김치컵",1600,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이_여우티5T",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_질러직화풍BBQ30g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뉴자이언트_떡볶이",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_버터크림소시지",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고흑임자죽용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고단호박죽용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반스팸김치덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥허니갈릭치밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마시는오트밀그린티",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마시는오트밀우리쌀",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반왕갈비탕460",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반차돌된장찌개460",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반차돌육개장460",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반백합미역국460",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신화_대왕오징어다리40g",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_오징어땅콩좋아해소",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO제주마늘라면컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_매콤불제육칼면",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_매콤불곱창칼면",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HJF_참나무훈제통목살",4300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_빅츄리2입",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뉴자이언트_어묵떡볶이",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("뉴자이언트_라볶이",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_샤인머스캣500g팩",13500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_샤인머스캣_컵_",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_맛있는라면컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_나가사끼짬뽕컵",1350,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_남도식한우미역국",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_안동식쇠고기국밥",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("더본_백종원크림컵떡볶이",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_깍두기철판볶음밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_닭갈비철판볶음밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_NEW와사비맛아몬드30",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마니커_핫함에빠진닭다리",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GG_트러플피자",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_고향만두샤오롱180g",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_의성마늘비엔나꼬치",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_오잉~쵹!",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칠갑_쌀떡국떡500g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칠갑_쌀떡볶이떡400g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마니커_오븐에빠진닭다리",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한맥_포켓치킨데리야끼맛",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한맥_포켓치킨양념치킨맛",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("녹차원_차전자피7T",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_불크림파스타",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_베이컨크림파스타",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_순두부치즈그라탕",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_얇은두부면100g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_모짜소떡핫도그",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_리얼바삭빅핫도그",2400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_브리또페퍼로니",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_김자반철판볶음밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_제일안주불돼지껍데기",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_제일안주소양불막창",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반들깨닭죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반백합죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_계란말이플레인150g",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_계란말이핫도그150g",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_다담된장찌개전용530g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에쓰푸드_이탈리안살라미",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_스모크치즈디스크",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_아페리프레다쥐르",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("구르메_아페리프프로방스",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_롱치즈프랑크소시지",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_롱육즙프랑크소시지",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO호로록수제비얼큰",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO호로록수제비시원",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_얇은피꽉찬매콤",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_얇은피꽉찬교자",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_밀누들떡볶이",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_숯불향닭강정매운맛",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_더블후랑크핫바",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_몬스터치즈후랑크",2100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_NEW군옥수수아몬드35",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_NEW허니버터아몬드30",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_뚜기네국물떡볶이",5300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_칼몬드파우치80g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_치즈킬바사소시지",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO_크래빗180g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO크래빗90g",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_다크스위트10T",4100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_맥심오리지날병100g",7400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_순보리차30T",2600,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_몬스터크랩72g",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_클램차우더",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_베이컨감자차우더",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_머쉬룸차우더",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_동물복지촉촉란2입",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_실속맥반석왕오징어",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반트러플쇠고기죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반트러플전복죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_실속커피땅콩100g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_냉장양반단호박죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_냉장양반밤단팥죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_모짜렐라치즈볼140G",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_냉장양반전복죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_냉장양반쇠고기죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_아삭옥수수250g",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반불닭마요덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_삼겹소시지볶음",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_숯불돼지바베큐",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_즉석삼계탕800g",15000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_함흥비빔냉면474g",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_동치미물냉면908g",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_오리파워업덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메모짜돈카츠450g",10000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메등심돈카츠450g",10000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메순살치킨550g",8000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_투머치즈샌드육포",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고갈비탕400g",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고스팸부대찌개460",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메함박152g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메치즈함박152g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_다진마늘150g",6100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("종가집_검은콩조림100g",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_깻잎지150g",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_메추리알장조림200g",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집포기김치3.3kg",30600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이_냉동이베리코립핑거",10800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이_냉동이베리코목심",10800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("UCI_트윅스스프레드",7500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("UCI_몰티져스스프레드",7500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_폭찹스테이크280g*2",8800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_그릴블랙퍼스트280g*2",8800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_목초란10구",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("스미_바나나_봉_1kg_",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_극한직화후랑크",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("세양_구운란2입",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집맛김치용기75g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_퀘이커오트밀누룽지",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_퀘이커오트밀구운김",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_명품쌀3kg",18000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_명품쌀1kg",7200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_옛날국수면",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오_옛날물엿1.2kg",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_소면",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_골드마요네스300g",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_백세카레약매100g",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_백세카레순한100g",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_카레매운맛100g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_미니케챂65g",700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_시저양고기",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_시저쇠고기참치",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마즈_시저불고기",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_뽀로로짜장소컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_하트치즈게티컵",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_하트짜라볶이컵",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사세_버팔로윙봉",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_블루베리100g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_고추참치비빔우동",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면건면사발",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칠갑_똑쌀떡국",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고김치왕교자385g",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고왕교자만두420g",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_훈제대란2입",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_치즈닭갈비",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_치즈오돌뼈",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_한입쏙계란말이치즈",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_슬라이스햄사각",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_체다치즈100g",1950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_실속구운쥐치포8마리",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야제육오돌뼈",6400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야매콤껍데기",6400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야마늘모듬곱창",6400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_스쿱샐감자마요",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_스쿱샐참치마요",2500,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_스쿱샐에그마요",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_마늘닭볶음탕용기",8500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_사골곰탕",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_소고기육개장",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_사골우거지국",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_녹차무쌈",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팜덕_흑마늘훈제삼겹",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팜덕_허브갈릭훈제오리",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_수란탁크림파스타",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_수란탁짜장면",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("더리얼_연어그레인프리",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_맛있는큰밥4입",9500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_덴마크트러플스트링",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하트_랩노쉬스트로베리",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이그_랩노쉬초콜릿",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_실속맥반석핫오징어",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_실속맥반석버터구이",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_앵그리짜파구리컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_순살학센슬라이스",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_하루한컵과일&견과",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_매콤불닭발",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_칼빔면",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_직화포차닭구이",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에스피_레몬2입팩",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("더본_백종원매콤컵떡볶이",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_순두부찌개양념140g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_부대찌개양념140g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_된장찌개양념140g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_연탄불고기양념140g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_바이탈홍초석류50ml",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_델몬트파인애플836g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_꽁치400g",7000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스_앵그리크림쫄면",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_질러더크레이지핫!",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진비빔면",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉오리지널50g",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("보승_한판모둠순대",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_상상디핑칩오리지널",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매크_본마망미니오렌지잼",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매크_본마망미니딸기잼",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_통모짜스트링치즈",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_미정당어묵떡볶이",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_마라훠궈백탕면",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_마라훠궈홍탕면",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_통모짜불닭덮밥",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_함박스테이크정식",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO신불닭비빔면컵",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO유산슬비빔면컵",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO유산슬덮밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_떡볶이양념150g",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_스팸200g*3입",12900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_대두유1.8L",8500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_뚝배기불고기양념150g",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설맛소금100g",600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설대두유1.5L",5700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_돼지불고기양념290g",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설남해굴소스350g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_허브맛솔트순한맛55g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설튀김가루500g",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설부침가루500g",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설포도씨유500ml",7200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설정백당1kg",2100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설중백당1kg",2400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_해찬들초고추장300g",2600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_해찬들사계절쌈장500g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_해찬들초고추장170g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_프락토올리고당700g",3100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_백설밀가루1kg",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_사계절쌈장170g",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_북어포",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_믹스너트캔",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_칼몬드캔",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_알땅콩캔",3600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머_믹스파티800g",9900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_꿀땅콩캔",3600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_양조간장500ml",4600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반구운김밥김",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_토마토파스타소스430",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_돼지고기장조림",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_폰타나페루치네면",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_가쓰오우동2인분",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_얼큰우동2인분",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_둥지비빔냉면",1700,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_둥지물냉면",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("경진_2배!빅꾸이맨",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥볼케이노치밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_국산찌개두부110g",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집맛김치1.6kg",16500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_맥심모카믹스100T",15900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_바닐라라떼8T",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_티라미수라떼8T",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_새우깡국물라볶이",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_영양삼계죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_맥심모카믹스20T",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_한입애베이컨70g",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고버섯야채죽",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고차돌된장찌개",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고돼지김치찌개",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉직화꼬치바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PSK_퓨어스펙오렌지6입봉",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("PSK_퓨어스펙오렌지2입",2600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_핑크퐁짜장떡볶이",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_핑크퐁토마토떡볶이",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집맛김치50g",850,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_맛있는밥6입",9500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_훈제계란2입",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_XO슈마이소라새우",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_XO슈마이고기",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_꽃보다오다리",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_살코기참치150g",3400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_쌀떡국용기",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_간장닭강정",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_매콤닭강정",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김천_깨끗한계란10입",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유성_유동골뱅이140g",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_슈프림치즈부리또",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_불고기치즈부리또",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_쇠고기버섯죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_전복새우죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("머거본_꿀땅콩70g",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_비바크부어스트",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO쫀득한떡볶이짜장",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO쫀득한떡볶이매운",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("티젠_유기농로스팅녹차20T",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("키다리_세이면잔치국수",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("키다리_세이면설렁탕",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_사골곰탕국물500ml",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아모제_레드커리덮밥",4300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_크리스피청포도컵",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_돼지김치찜용기",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_우거지뼈해장국용기",6500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_한입에꼬치바매운맛",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반버터장조림비빔밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반김치날치알밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_앵그리너구리컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("은하수산_숙성홍어회",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_불똥집짜글이",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("MDS_불곱창짜글이",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("보승_한컵얼큰술국",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_오잉~츄!",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_치폴레치즈팡50g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_맥스치즈팡50g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_3000귤",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_삼양라면오리지널컵",1100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_연한고추장불고기",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_연한간장불고기",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고수제만두김치",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고수제만두고기",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_매콤칠리닭가슴살",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_훈제닭가슴살",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_오리지널닭가슴살",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_배즙숙성후랑크",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_하루한컵헬스",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸드_하루한컵뷰티",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웰팜_감자합니다야채",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웰팜_감자합니다",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_프로틴쉐이크미숫",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_프로틴쉐이크초코",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_바베큐오징어30g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_더왕뚜껑순한맛컵",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_쫄깃한장조림달걀",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("편스토랑_마장면컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("맥널티_디카페인원컵",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_오라면사발컵",800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_치킨박스고추크런치",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_덴마크라이트스트링",1300,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_BBQ칠리",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_BBQ오리지널",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("세척사과",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("꽃샘_호두아몬드율무8티",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고배추김치200g",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_킬바사소시지",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_우노콤비네이션",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_우노불고기피자",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에스피_씨없는적포도400g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에스피_씨없는청포도400g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_불닭마요네즈250g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("영찬_달콤한직화육포",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고통단팥죽용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_짜라볶이컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("공덕_한입꿀고구마800g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_동의반숙란3입",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_청양닭가슴살후랑크",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_김치칼국수밥컵",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_바지락칼국수밥컵",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_딸기500g",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥김치참치덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥매콤낙지덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_더배터질라면왕컵",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("길림_흑당밀크티아몬드",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("큐원_흑미꿀호떡133g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_메추리알쏙쏙5입",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_뿌려먹는모짜렐라",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("스미_반값바나나",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("담터_쌍화차플러스원컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풍림_에그롤햄",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풍림_에그롤치즈",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨즈_레몬꿀차원컵",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨즈_헤이즐넛라떼원컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_치즈촘촘육포",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_꼬마쥐포구이",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_화끈불닭발",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_고당도하우스감귤500",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_방울토마토컵",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_ASMR매콤크림면",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반사골곰탕국밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_칠리소시지",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김선생_가락떡볶이",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_크림파스타소스450g",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_명란크림파스타컵",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한일_트러플크림파스타컵",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_반값사과1kg",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_맛있는밥150g",1550,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("고려_오리지널육포",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_더매운맛라면오리",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_ASMR쫀득간장마요면",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("영찬_통육포오리지널",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_올리브유쥐포",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마시는오트밀서리태",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥오삼불고기덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주_천하장사매콤달콤바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주_천하장사오리지널바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_직화통삼겹슬라이스",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살갈릭",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_머릿고기수육",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_달콤간장삼겹살",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("본죽_남도꼬막무침",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_구운육포",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_오리지널육포",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_친친오리지널봉70g",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_적포도_컵_",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_얇은피김치만두",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_얇은피고기만두",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뗄_자이언트치즈핫도그",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_자두2입",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉치즈어랏40g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살블랙페퍼",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살오리지널",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("스미_슈퍼사이즈바나나1입",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_마라탕면컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_오징어채볶음60g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_쇠고기장조림130g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_훈제닭다리",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_바베큐오징어",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_단호박죽285g",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥소시지카레",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반설렁탕밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고닭백숙죽용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_교자만두200g",2500,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_짜파게티라볶이용기",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반들기름김",600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_콘앤스윗치즈45g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_덴마크피자치즈25g",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("세양_1등급구운란4입",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_리얼로스트랍스터맛",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_ASMR꾸덕쫀득크림면",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야매운껍데기",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("델몬트_바나나2입",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_대패왕다리오징어",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고야채죽용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고소고기죽용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고전복죽용기",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_돌산갓김치90g",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_육즙에빠져바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반닭곰탕밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반치킨마요덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_상상버터오징어",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_의성마늘프랑크빅90g",2100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_몬스터크랩레그120g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_미정당비엔나떡볶이",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("보승_매운불껍데기",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행_참한일판란30입",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥궁중갈비찜",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_천하장사빅70g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_켄터키프랑크소시지",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_오삼불고기",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_당도선별세척사과",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_부침두부300g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_찌개두부300g",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉빅소시지150G",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_미니허니머스타드",700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_미니스위트칠리",700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_미니갈릭마요디핑",700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("담터_벚꽃라떼원컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_한입에꼬치바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_오잉스틱",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_하선정멸치액젓400g",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_재래식된장500g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_태양초고추장500g",9000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마시는오트밀그레인",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_훈숙이2입",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반210g*8입",12900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("선명_하루견과옐로우20g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_몬스터크랩142g",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면건면",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_무파마탕면",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고전복죽",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고소고기죽",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_만능비빔장시그니처",5700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_자이언트쫄볶이",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_고추장삼겹살",6900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_포차불막창",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("태경_우거지뼈해장국",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야매운곱창볶음",7900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_육식본능비빔불고기",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_리얼바다오징어",8500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_고향만두치즈갈비",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼경_델몬트후르츠850g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_매콤야끼소바라면대",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맛고구마60g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨엔_딸기250g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_고소한근위볶음",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("보승_한컵순대곱창",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO컵두부된장국",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하늘_포보베트남쌀국수",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("이가_마라탕면",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_불닭소스200g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_쫄볶이불닭볶음면컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥설렁탕국밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조인_신선란한알",600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_팔도비빔면",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_장자미니족발",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_장자슬라이스족발",9500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유성_유동골뱅이230g",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바나나1입",700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("녹차원_어묵티매운맛원컵",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("녹차원_어묵티원컵",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_김라면컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_참참참계란탕면큰컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_미역국라면컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반참기름김",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_까르보불닭떡볶이",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_불닭떡볶이",3000,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_오감포차칠리새우",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_한입피자고르곤졸라",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_한입피자콤비네이션",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_출출양파감자라면",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨즈_한컵우유맛",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("담터_호두아몬드율무원컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("본죽_제주산안심장조림",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_진한참기름110ml",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_허니레몬블랙티",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥버터장조림",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_삼양라면치즈큰컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고깍두기볶음밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨즈_생강꿀차",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨즈_한라봉유자꿀차",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메핫스파이시미트볼",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_육개장컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아모제_매콤삼겹덮밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반스팸마요덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진라면순한맛",720,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진라면매운맛",720,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반볶은김치덮밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥부대찌개밥",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_스파게티토마토",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신화_노가리더바삭",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_롱에센뽀득프랑크",2400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메치즈함박스테이크",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("스미_감숙왕바나나2입",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_구운한치",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반200g*3입",5300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_스모크치킨",3700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_옛날삼계탕900g",10000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("유성_유동번데기130g",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_달콤데리야끼치킨",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_지중해황도410g",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("본죽_보양삼계죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이랜드_냉동삼겹살",8000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_연와사비35g",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_연겨자35g",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_옛날당면300g",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_돈까스소스290g",2600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_순후추100g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야달콤쫄깃육포",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_동물복지훈제란2입",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_순창고추장육포",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반낙지콩나물비빔밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵누들매콤소컵",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("티젠_보이차 20T",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_스모크닭다리2입",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_상상안심육포",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥참치마요덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아워홈_매콤제육불고기",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_치즈큐빅플레인",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진짜쫄면",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반매일잡곡밥210g",2650,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야무뼈닭발",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_안주야불막창",8900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아라움_통새우튀김",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_짜장불닭볶음면큰컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_참깨라면소컵",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("장충동_머릿고기",8500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥돌솥비빔밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_밀레니엄안주",8200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_슬라이스오징어",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_숏다리",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_리얼동해당일오징어",9900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_스팸200g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_스팸340g",7500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고소고기무국500g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고설렁탕500g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_휠터치3입소시지",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_숯불후랑크꼬치",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_새송이쇠고기죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉구운마늘후랑크",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반직화불고기덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("선명_멸치아몬드봉지",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진라면순한소컵",750,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_스노우크랩킹140g",3100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_화이트골드150T",24000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면블랙봉지",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_까르보불닭볶음면",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_까르보불닭큰컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_소시지야채볶음",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고김치볶음80g",1400,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면블랙사발",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고육개장500g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고소고기미역국500",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥톡톡김치알밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마늘앤에센뽀득2입",3400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO_피자그라탕",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_매콤한무뼈닭발",6700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵피자콤비네이션",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반밤단팥죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아침_슬라이스고구마",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_고메함박스테이크200g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_베트남쌀국수컵",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_참치크래커고소한맛",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_훈제메추리알3입",800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_스위스미스머쉬멜로",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_감자탕큰사발",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_명품다시다100g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_오징어전기구이",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_세가지맛오징어",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_문어맛오징어",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("돌_건망고80g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집볶음김치190g",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집맛김치용기130g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_불닭볶음면",1050,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_삼양라면",800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_목장스트링치즈",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_닭가슴살삼계탕",6700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_영양닭죽285g",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO매운까르보볶이",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO콘치즈그라탕",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고배추김치용기50g",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_맛있는큰밥300g",2600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제니코_치즈파티모짜렐라",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_토마토케챂300g",2100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_딸기잼300g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_크림스프80g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_쇠고기스프80g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_육개장사발면",850,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("김천_영양란10입",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_튀김우동큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_자연숙성진간장500ml",2750,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반철판제육덮밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_마늘숙성떡갈비맛바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고김치왕교자",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하림_반마리훈제치킨",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이_찡오랑땅콩버터맛",4100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아이스올리_순얼음800g",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아이스올리_순얼음2.5kg",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("델몬트_조각파인애플180g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_해표카놀라유250ml",2400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_압착올리브유250ml",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉청양고추후랑크",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("청포도400g팩",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오렌지5입망",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오렌지5입망",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반중화마파두부덮밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반올리브유김12입",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_리챔200g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_안성탕면",750,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_너구리얼큰",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면소컵6입",4400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면소컵",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_짜파게티",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_신라면",830,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_오징어짬뽕",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_사천짜파게티",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_너구리얼큰소컵",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_무파마큰사발",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("에코_반숙계란2입",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_모닝참한란4입",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_유부초밥",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_국산콩나물250g",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_콩나물220g",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_소가찌개두부290g",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_소가부침두부290g",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_모닝버터200g",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반야채죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반쇠고기죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반참치죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_고추참치150g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_고추참치100g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_김치찌개참치150g",4000,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_동원참치250g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_동원참치150g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_동원참치100g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("밀감3입_망_",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO컵육개장",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해밀_특란6입",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_짬뽕어묵탕",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("세양_특란10입",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조인_특란10입",400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_맛있는밥4입",6600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_BIG새우맛바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_종가집김치찌개면",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_컵밥제육덮밥",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_상상비프앤치즈40g",5500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_왕뚜껑",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_오잉",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_오징어땅콩좋아해대",5200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_김치도시락",850,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_간짬뽕컵",1350,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반콩나물국밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("신화_쥐포구이채",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_야채참치150g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고찐만두청양고추",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한울_볶음김치100g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미션_세부망고100g",5000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_팔도비빔면컵",1050,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_치즈불닭볶음면컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치카페믹스20T",4700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_김치사발면",850,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_새우볶음밥",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO크래미아샐러드",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반직화볶음짜장덮밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맛있는소시지160g",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉치즈70g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고찐만두168g",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_훈제계란2입",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_옛날누룽지용기",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진짬뽕컵",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진라면순한컵",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("고려_돈육포매운맛",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반강된장보리비빔밥",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정화_노래방구이구이",6000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("경진_꾸이맨30g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진짬뽕",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_꾸이맨매콤한맛30g",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_시원한오뎅한그릇",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_스키니오징어25g",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제니코_라이트스트링치즈",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제니코_스트링치즈",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_육개장큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제이_직화오돌뼈200g",5900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_매콤한깻잎",2150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_메추리알장조림",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_오징어와땅콩",8500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_매콤달콤우동볶이",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_컵반미역국밥",4200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("본죽_쇠고기죽",3600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_고향만두415g",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_리얼군밤츄100g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO청양고추라면",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO속초홍게라면",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_키스틱55g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_쪄먹는야채믹스",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집맛김치200g",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_빅숏다리오리지널",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_미니비엔나70g",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_라면볶이컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_사천짜파게티큰사발",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집맛김치400g",4900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_의성마늘무안양파2입",3400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO콘샐러드",2600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고왕교자만두",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉숯불구이맛핫바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_화이트골드믹스20T",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_현미녹차25T",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_둥글레차25T",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_숏바디통구이",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_숏바디슬라이스",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_우육탕큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_모닝두부오리엔탈",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한울_꼬마단무지",750,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_얼큰우동컵",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_큰햇반300g",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_천하장사28g",900,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_허니버터그릴바",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("본죽_전복버섯죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팜스_바나나2입",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바나나2입",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한스_참치볶음김치80g",1100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반올리브유김",600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제니코_스모크스트링치즈",1400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_3분쇠고기간짜장",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반210g",1950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("선명_헤이즐넛땅콩봉지",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_스윗아메리카원컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("장충동_쫄깃한편육",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("세척사과대",2400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_푸짐한얼큰어묵탕",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_생생우동컵",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("감말랭이160g팩",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉크레이지핫핫바",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_숯불구이비엔나170g",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_스팸김치볶음밥 ",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_오징어짬뽕큰사발",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_비비고썰은배추김치60g",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_김치큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_사리곰탕큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("행복_동의훈제란3입",2500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_오징어짬뽕소컵",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_튀김우동소컵",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_새우탕소컵",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_스낵면컵",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_새우탕큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_짜파게티큰사발",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반작은공기130g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("선명_하루견과요거트",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한성_몬스터후랑크",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("진주햄_천하장사50g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_짜파게티범벅",850,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_사과식초360ml",1100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("사조_해물즐겨바",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_고구마츄",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_숯불향바베큐바",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_숯불향닭강정",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반발아현미밥210g",2650,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_햇반흑미밥210g",2650,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO시원한바지락칼국수",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO치즈맛라면",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GG_자이언트피자",2700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_3분카레매운맛",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_피자떡볶이",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_한입쏙쏙미트볼",3000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_가쓰오우동컵",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_국물떡볶이",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼양_불닭볶음면컵",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO자이언트핫도그",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반영양닭죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_열라면컵",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_치즈볶이컵",1100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반호박죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오_열라면봉지",750,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_맛있는밥210g",1850,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_스파게티컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진라면매운소컵",750,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_도시락",850,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_참깨라면",1100,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_너구리큰사발",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_참깨라면컵",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_진라면매운컵",950,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("성찬_깜밥누룽지탕컵",1700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("성찬_깜밥누룽지끓임용",2300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_짬뽕왕뚜껑",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_김치왕뚜껑",1150,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_까르보나라스파게티",4300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_볼로네이즈스파게티",4300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반전복죽",3900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_전복죽",3200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_꼬꼬면컵",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_맥심화이트골드원컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팜스_세척사과",1500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_맥심모카골드원컵",900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오뚜기_고추참치150g",2800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("네슬레_핫초코오리지널10T",5400,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_매운고추참치150g",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("모_모카카푸치노",700,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("대상_종가집다진마늘150g",4800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨_핫쵸코원컵",1000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_얼큰오뎅한그릇",2900,100,"food");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_대두유500ml",2900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농_친환경청량&풋고추",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_덴마크스트링치즈",1300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일미_한입쏙비타단무지60g",500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_마일드아메리카노10T",3800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_국산꽃소금200g",1200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("장충동_순살족발",6800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("영찬_먹기좋은육포채",2200,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_빅팜60g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯_의성마늘프랑크",1800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_질러직화육포",5800,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯_의성마늘프랑크2입",3300,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("선명_믹스너트봉지",2000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맛밤80g",3500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_숯불갈비맛후랑크",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_맥스봉치즈50g",1600,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("썬푸드_한치와땅콩",4500,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한양_숏다리매운맛",1900,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("샘표_질러부드러운육포",4000,100,"food");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마시는식사비건그레인",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_모닝케어D",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO미네랄워터P1L",900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("파워마운틴대P",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_스페셜티마일드250ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("야쿠_오늘의야채오리250ml",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_초코에몽250ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_미닛사과스파클링캔345",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오션스프레크랜베리",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_커핑콰트로블랙P350",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_초코우유200ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비카페타임라떼",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트로피망고캔355ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨복숭아930ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_스프라이트P1.5L",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_커피300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_허쉬초코드링크235ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타블랙컵325",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯_트로피패션후르츠캔355",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO블루레몬에이드360",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아이시스8.0P500ml",850,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_대추쌍화병150ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핫식스자몽캔250ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타바닐라빈325",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_검은콩우유300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20_HEYROO빅바나나우유500",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_힘찬헛개차P340ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_프로틴플레인210ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_로스터리아몬드라떼",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_포도봉봉캔340ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_올데이아메리카노",3900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타프리미엄390ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_베지밀A병",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_오랑지나P420ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트로피파인캔355ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_ABC주스",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_밀키스P1.5L",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_불가리스자연사과",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("다논_액티비아업플레인210",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_몬스터에너지캔355ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_초코에몽아이스",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_비타500아이스",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_블랙슈가밀크티250ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_로얄밀크티250ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_초코츄러스라떼",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_자몽허니블랙티",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_귀리두유팩",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_레드불화이트250ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("delaffe청포도아이스",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("메이크비_빡!텐션쇼크캔",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_요플레only3플레인",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조지아_블랙아이스230ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("조지아_아메리카노아이스",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_스프라이트제로캔355",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타그란데라떼",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타그란데아메",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_라잇미닛코코넛팩",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_1L복숭아아이스티",3300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_1L헤이즐넛향",3300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_1L블랙아메리카노",3300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_1L아메리카노스위트",3300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_벤티블랙아메리카노",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_벤티아메리카노스위",1600,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_우유얌초코300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_우유얌딸기300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("야쿠_연남방앗간참깨라떼",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("야쿠_연남방앗간딸기라떼",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_흑미차500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_비요뜨초코팝",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이_귤먹은여우티500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이트_자몽토닉워터300",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("del_벤티컵얼음400g",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_수박바아이스",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_스크류바아이스",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_믹스커피",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_카라멜마끼야또",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_아이스카페라떼",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_디카페인블랙",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_자몽허니블랙티",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_타트체리에이드",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_빅청포도에이드",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_빅레몬아이스티",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_빅복숭아아이스티",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_복숭아아이스티",700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_블루레몬에이드",700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_빅헤이즐넛향",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_헤이즐넛향",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_빅블랙아메리카노",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_블랙아메리카노",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_빅아메리카노스위트",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("21델_아메리카노스위트",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_밀크티맛단지",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은납작복숭아340",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무_잇츠프로틴디카페인",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_잇츠프로틴초코",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_환타파인애플캔250",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비카페헤이즐넛",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_크래프트콜드라떼370",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_크래프트콜드블랙370",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_블랙보리우유300",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_새싹보리우유300",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_드링킹요구푸룬310ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_너티초코우유300",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_시나몬초코우유300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_비요뜨초코크리스피",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바이오알로에120g",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성사이다제로P1.5",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성사이다제로P500",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마시는식사비건그레인",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("마시는식사비건카카오",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_펩시제로P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오비_카스제로캔355ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯_트로피패션후르츠캔355",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙_바나나우유4입",5600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_델몬트포도400ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_델몬트오렌지400ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_올데이헤이즐넛1L",3900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_올데이아메리카노",3900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯_아이시스에코500ml*20",18000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("OKF_골드유자500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙_요플레토핑화이트초코",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("와일드베리_링곤베리350ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("다논_요거톡스타볼",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("다논_요거톡초코그래놀라",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_씨그램애플P350ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_요거밀카카오그래놀",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_요거밀왕초코링",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_크래프트스윗블랙470",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_크래프트밀크티470ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙_쥬시쿨청포도에이드",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_청미채옐로우200ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_청미채그린200ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_검은콩고칼슘병",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_갈아만든배P500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_미닛포도P350ml",1950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("OKF_요구르트스파클링500",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오가다_배도라지티180ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_설빙인절미라떼250",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_설빙흑임자라떼250",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핫식스팬시캔디250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_양반배식혜P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_목까지톡쏘는배P500",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼육_검은콩호두아몬드병",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_살롱밀크티300ml",1500,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비헤이즐넛500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_얼라이브청포도250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카제로P1.5L",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20델_홍시에이드",700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_셀렉스프로틴초코",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("85도씨대만소금커피300ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("OKF_레몬C스파클링500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_타트체리250ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_파워쉐이크곡물250",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_파워쉐이크초코250",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한독_레디큐프로캔120ml",6000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("VIDA_라임모히또325ml ",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("VIDA_클리어레몬325ml ",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_강릉커피블랙250ml",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_강릉커피라떼250ml",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_귀리우유190ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_흑임자우유190ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_나랑드사이다캔245ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칭따오무알콜캔330ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_하이프로틴초코",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서강_홍루이젠밀크티휴",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_델몬트제주감귤1.5L",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_제주용암수530ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피심플리블랙240",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은망고1.5L",4100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은사과1.5L",3700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("OKF_워터멜론500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20델_수박에이드",700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_몬스터파라다이스캔",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_델몬트오렌지1.5L",4300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_델몬트알로에1.5L",4100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_델몬트포도1.5L",4300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은토마토1.5L",3700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_닥터유단백질바나",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("오리온_닥터유단백질초코",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_네버스탑500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("del_빅볼컵얼음160g",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("쟈뎅_new오렌지자몽블랙티",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핫식스더킹포스",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_흑임자우유250ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_호랑이라떼300ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_브루빈디카라떼",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_브루빈디카아메",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_미닛오렌지P1.5L",4500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_요구르트65ml5입",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_멸균흰우유200ml",900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_맛있는우유딸기300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타민트라임325",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("바이_여우티500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_2%자두500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_달고나라떼250ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20_HEYROO저지방흰우유300",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20_HEYROO빅딸기우유500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피너티카라멜",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_커핑콰트로스윗P350",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_커핑콰트로블랙P350",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_ABC주스",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_듀오안플레인150ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스돌체병",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("OKF_골드키위500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯_칠성사이다복숭아P500",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성사이다청귤P500ml",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20_HEYROO빅바나나우유500",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO진한홍삼꿀물",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO헛개열매꿀물",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO아카시아꿀물",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_모닝케어D",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_모닝케어H",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_뽀로로딸기우유",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_뽀로로바나나우유",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치블랙글레이즈",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_로스터리흑임자라떼",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_로스터리아몬드라떼",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("설운_시원얼음3kg",3650,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("설운_시원얼음1kg",1850,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_파워에이드볼츠600ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_크래프트블랙P800ml",3700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_프로틴딸기바나나",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_프로틴플레인210ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_스페셜티예가체프",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_스페셜티킬리만자로",2500,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업과일야채그린컵",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO미네랄워터500ml",600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_오가닉포도당근125ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_오가닉사과당근125ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_밀키스P1.5L",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_헛개수EX500ml",3000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_쿨피스복숭아450ml",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("야쿠_BTS바닐라라떼270ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("야쿠_BTS아메리카노270ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_바나나우유300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_비피더스블루베리",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_비피더스사과300ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타디카페인325",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마운틴듀355ml캔",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_채움사과210ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_베지밀팩A",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_티즐피치우롱티500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_티즐유자그린티500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_박카스F",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비그란데P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라벚꽃캔250ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정관장_테이크5체리피치",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정관장_테이크5망고키위",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_흑임자우유750ml",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_맛있는우유900ml*2입",4800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20델_빅블랙아메리카노",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("20델_블랙아메리카노",700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_초록매실P340ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업식이섬유플랜",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업콜라겐플랜",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("OKF_샤인머스켓500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_보성말차라떼500ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_데미소다청포도250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은알로에P1.5L",4100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_루카스나인라떼250ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_두유검은콩팩190ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_아몬드브리즈프로틴",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("파스퇴_위편한하루150ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_아카페라UP바닐350",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_닥터캡슐사과",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_닥터캡슐플레인",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("쟈뎅_로얄헤이즐넛1.1L",3900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("쟈뎅_아메리카노블랙1.1L",3900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_깨수깡캔160ml",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치킬링샷라떼500",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치킬링샷아메500",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정관장_홍삼원D병100ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코코팜피치캔240ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_토레타P900ml",2600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_환타파인P600ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_지리산수P500ml",850,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_흑당밀크티270ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_흑당카페라떼250ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_갈배사이다P500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("야쿠_오늘의야채퍼플250ml",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("야쿠_오늘의야채오리250ml",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_생초콜릿라떼250",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_몬스터파이프캔355ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스콜드블랙325",3000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_비타500로열병120ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트레비금귤P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_엔요대용량280ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_흑당밀크티250ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_비요뜨쿠키앤크림",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_새싹보리P500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스스무스270ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_2%복숭아500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_브라운슈가라떼",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_브라운슈가밀크티",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이트_블랙보리라이트",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_콘트라베이스스위트500",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_마스터라떼P500ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_마스터블랙P500ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("고려은단_스파클링비타민C",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_흰우유300ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_돼지감자차P500ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_콩카페연유라떼",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_콩카페코코넛라떼",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_덴마크복숭아녹차",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_덴마크레몬녹차",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("모구모구_포도젤리320ml",1500,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_스프라이트캔355ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_크래프트라떼P470ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_크래프트아메P470ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_심플리라떼360ml",2400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_커핑모카라떼300ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칸타타_헤이즐넛향아이스",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("칸타타_아메리카노아이스",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_뽀로로보리차P220ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_아침햇살P340ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_잇츠라떼바닐라320",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("고려은단_허니유자비타민C",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핑크퐁오렌망고235ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("장수_리얼깔라만시200ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_상하유기농멸균200ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_커핑로드카페봉봉",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핫식스더킹펀치",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핫식스더킹파워",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_따옴청귤한라봉235",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비솔트240ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_평창수프리미엄500ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성사이다캔330ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_2%아쿠아340ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_미숫가루우유730ml",4000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_딸기맛우유240ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_조지아스윗아메캔",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_히비스커스P500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타로슈거",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이트_토닉워터깔라만시P",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이트_진로토닉워터300ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_얼라이브오렌지250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨감귤에이드",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨사과에이드",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("어른우유검은콩미숫가루",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_비요뜨초코링143g",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_맛있는우유900ml",2650,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_맛있는우유500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_맛있는우유200ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스파이크275ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_펩시콜라캔330ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_바나나우유240ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_포카리스웨트캔245ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_딸기꿀딴지180ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피볼드에스프",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피마일드에스프",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피트리플에스프",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_코코팜포도캔340ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("del_빅컵얼음230g",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("del_컵얼음180g",600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_커피300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_딸기우유300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_초코우유300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라캔350ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_제주삼다수P2L",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_제주삼다수P500ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_요플레토핑초코",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_목장흰우유1L",3300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_콘트라베이스라떼500",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이트_석수2L6입",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_흑삼한뿌리병",7000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("고려은단_비타민C1000병",700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_훼미리종합선물세트",12000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_몸에좋은선물세트",12000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_밀키스캔340ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성로어슈거캔250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_파워에이드퍼플600ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정관장_아이키커사과",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_식후비법W차P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제주_삼다생얼음3kg",3200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("제주_삼다생얼음1kg",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_오란씨파인애플P1.5L",2700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_포카리스웨트P1.5L",3500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_포카리스웨트P620ml",2300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일화_맥콜P1.5L",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_베지밀B팩950ml",3000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트로피파인캔355ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_씨그램레몬P350ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_콘트라베이스P500ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_비타500병180ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("삼립_오생수P320ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_포카리이온워터P500",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울F&B_패밀리요구르트",2300,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_몬스터시트라캔355ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_오랑지나P420ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO딸기주스210ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스에스프레270",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_카프리사파리200ml",900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("산펠레그리노500ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_돌얼음2.5kg",3950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("풀무원_돌얼음800g",1850,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_비타500병100ml",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("모구모구_리치젤리320ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_환타플러스씨레몬캔",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_조지아고티카블랙390",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_아침에주스오렌지210",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_펩시스트롱P400ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_저지방우유900ml",2600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_흰우유900ml",2600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피심플리라떼240",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피심플리아메240",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("OKF_알로에베라킹500ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("다논_액티비아업복숭아",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_아침에주스포도210ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_두유99.89팩190ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_네스퀵초코드링크",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_포도봉봉캔340ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GET콜드브루아메리카노",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("부산_위너흰우유900ml2입",4000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이트_블랙보리P520ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_소화가잘되는우유190",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_보성말차P500ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_컨디션CEO병150ml",10000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_꿀홍삼병180ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_꿀초록매실병180ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_대추쌍화병150ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("연세_마카다미아초코190ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_속까지부드러운꿀배캔",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빽다방_바니바닐라떼P300",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_카페라떼로어슈거",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_아몬드브리즈190ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("가야_제주감귤농장P340ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("가야_토마토농장P340mL",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_츄파춥스캔오렌지345ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_아몬드브리즈초콜릿",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타프리미엄390ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타아메리카노390",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_2%아쿠아P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일동_카카오닙스차P500ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("모구모구_복숭아젤리320ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타카라멜컵",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_위생천병",700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_미닛사과스파클링캔345",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨청포도450ml",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성스트롱사이다P400ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_데미소다자몽P340ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_힘찬헛개차P1L",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_아카페라UP라떼350",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_아카페라UP아메350",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO오렌지270ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO아메리카노P1L",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_레드불캔355ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO빅메론우유500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_맥심모카믹스150T",23000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일화_초정탄산수P500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라제로캔250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라제로P500ml",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라P1.5L",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_레드불캔250ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타바닐라빈325",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_갈아만든배캔340ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바이오드링킹블루250",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_토레타캔240ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨자두930ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("미성_허쉬핫초코원컵",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_드링킹복숭아310ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GET헤이즐넛향원컵",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GET아메리카노원컵",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_얼라이브망고250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_얼라이브자몽250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_흰우유200ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_저지방우유500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_저지방우유200ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_흰우유1L",2700,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_흰우유500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치돌체라떼컵250",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타콜드브루275ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("연세_마카다미아초코500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핫식스자몽캔250ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_미니마일드아메10T",2600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("카누_미니다크아메리카노10T",2600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스라떼컵270ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라캔355ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_백산수P2L",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오션스프레크랜베리",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_오션스프레루비레드",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_토레타P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타블랙컵325",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타드립라떼325",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_몬스터울트라에너지",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_스프라이트P1.5L",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_옥수수수염P1L",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빽다방_황금라떼P300",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피마스터라떼380",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스커피라떼컵",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스더블샷275ml",3000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스밀크병",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스모카병",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_스타벅스더블샷캔",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("GET더치커피워터P330ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바이오플레인150g",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바이오드링킹플레인",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바이오드링킹딸기250",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성사이다P500ml",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("거림_밀크티라떼320g",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("거림_녹차라떼320g",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_비락식혜캔238ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO사과주스270ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_초코꿀단지180ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("그래미_여명808캔",5500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_몬스터에너지캔355ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_베지밀B검은콩병",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("씨즈_핫초코원컵",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_진쌍화병",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("쟈뎅_카페모카",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_초코에몽캔200ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_요플레블루베리200",1950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_요플레복숭아180g",1950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_요플레딸기180g",1950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_베지밀A병",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_제주감귤P500ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_초가을우엉차P500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO믹스커피P1L",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨자두450ml",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO블루레몬에이드360",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨파인450ml",800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업오렌지200ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업사과200ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_뽀로로밀크맛235ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_씨그램라임P350ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_허쉬초코쿠키앤크림",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_딸기크림치즈라떼",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_오곡라떼",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_카페베네라떼300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("현대_미에로화이바병210ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO카페모카컵300ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO카페라떼컵300ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_아카페라바닐라P",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_뽀로로딸기맛P235ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일화_맥콜P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아이시스8.0P2L",1550,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_게토레이레몬P600ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_스페셜티모카컵250ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_초코에몽250ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO빅요구르트450",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_베지밀국산검은콩",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_립톤복숭아P500ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO망고주스270ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트로피망고캔355ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_허쉬초코드링크235ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_오로나민C병120ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_초코우유200ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치카라멜컵250",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트레비라임P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트레비레몬P500ml",1800,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("CJ_홍삼한뿌리병",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_조지아라떼캔270ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("다논_액티비아업플레인210",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO미네랄워터P1L",900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_콜드포도250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_콜드오렌지250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아임리얼_토마토190ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("아임리얼_딸기190ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("팔도_비락식혜P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_데자와밀크티캔240ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_썬키스트모과병280ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_조지아블랙캔270ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치에스프레소250",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_뷰핏레몬P350ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO빅요구르트270ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_데일리씨레몬워터P",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피아메리카노380ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피더블랙380ml",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("한독_레디큐캔120ml",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정관장_홍삼원파우치100ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_레몬에이드P350",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_파워에이드P600ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_핫식스캔250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타아메리카노275",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타프리미엄캔",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO자몽270ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_파워에이드캔240ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_오란씨파인애플캔250",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라캔250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_펩시콜라캔250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_옥수수수염P500ml",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_스페셜티마일드250ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("페리에_라임탄산병330ml",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_아이시스8.0P500ml",850,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_비타민워터파워씨",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("비타민워터에너지",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업과일야채레드",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO흰우유1L",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO빅커피500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO빅초코우유500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("다논_액티비아업딸기210ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_딸기우유200ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("서울_커피200ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_불가리스자연사과",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_불가리스자연딸기",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("파스퇴_쾌변포도요구르트",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("파스퇴_쾌변키위요구르트",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("파스퇴_쾌변사과요구르트",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES (" 푸르밀_가나쵸코우유300ml ",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_우유속딸기",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("푸르밀_검은콩우유300ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_요플레플레인180g",1950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_우유속코코아",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨복숭아180ml",400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨복숭아930ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_드링킹요구사과310ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_바나나우유라이트",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_커피속모카",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_드링킹요구딸기310ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_쥬시쿨자두180ml",400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동_드링킹요구플레인310ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동원_드링킹요구베리310ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_초코에몽드링크",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_이오20s135ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HEYROO미네랄워터P2L",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_비타500캔240ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_검은콩베지밀팩",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_초록매실병180ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_컨디션레이디병",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치카페오레캔",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_백산수P500ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_2%부족할때복숭아캔",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_옥수수수염P340ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("파워오투오렌지레몬",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_헛개수P1L",2500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타모카",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성사이다캔250ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("환타오렌지대P",2800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("파워마운틴대P",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_평창수P2L",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_게토레이레몬P1.5L",3200,100,"drink");

INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_펩시콜라P1.5L",2900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칠성사이다P1.5L",3600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_카프리오렌지200ml",900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_조지아오리지널캔",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_태양의마테차P500ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_힘찬헛개차P340ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타스모키",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진꿀홍삼병",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_웰치포도캔355ml",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("일화_맥콜캔250ml",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("하이트제로캔_무알콜_",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("농심_웰치화이트포도355ml",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비카페타임아메",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_에비앙P500ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피더블랙캔",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피마스터라떼275",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_내사랑유자P280ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_맛있는두유검은콩병",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_바리스타에스프레소",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피마스터라떼캔",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_헛개파워병",4500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_헛개수P500ml",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타카라멜275ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("정식품_베지밀B병",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_카페라떼마일드컵",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_17차P500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("광동_힘찬헛개차P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_하늘보리P1L",2000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_미닛오렌지P350ml",1950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_펩시콜라P600ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_데미소다애플캔250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_오곡누룽지P500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_하늘보리P500ml",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_코카콜라P500ml",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은감귤병180ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은알로에병180ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타프리미엄275ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_립톤복숭아캔240ml",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("현대_미에로화이바P350ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_카페라떼카라멜컵",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("빙그레_아카페라카라멜P",1600,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치카푸치노컵",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("HK_컨디션파워병",5000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동아_데미소다피치캔250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치카페오레컵",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("남양_프렌치카라멜컵",1500,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_자연은알로에P500ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("해태_아침에사과P500ml",1700,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피아메리카노캔",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업과일야채퍼플",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("매일_썬업과일야채녹황",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_마운틴듀캔250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_밀키스캔250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_조지아맥스캔",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_조지아카페라떼캔",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_스프라이트P500ml",1800,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_스프라이트캔250ml",1400,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_환타오렌지캔250ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비캔",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("코카_환타오렌지P600ml",1900,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_트로피애플캔355ml",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_밀키스P500ml",2100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_레쓰비카페타임라떼",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_게토레이레몬캔240ml",950,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피더블랙275ml",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_실론티캔250ml",1100,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("솔의눈캔",1200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("동서_티오피아메리카노275",2200,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("롯데_칸타타아메리카노캔",1300,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("웅진_하늘보리P340ml",1000,100,"drink");
INSERT INTO Item_info (Product_name, Price, Qty, Category) VALUES ("가야_알로에농장P340ml",1000,100,"drink");

In [110]:
mydb.commit()